# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/account/{name}/token operations"""

import logging
from typing import Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def post_acct_svc_new_token(path_name: str, body_expires_in: int = None, body_id: str = None, body_name: str = None) -> Any:
  """
  CreateToken creates a token

  OpenAPI Description:


  Args:

      path_name (str): OpenAPI parameter corresponding to 'path_name'

      body_expires_in (int): OpenAPI parameter corresponding to 'body_expires_in'

      body_id (str): OpenAPI parameter corresponding to 'body_id'

      body_name (str): OpenAPI parameter corresponding to 'body_name'


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/account/{name}/token")

  params = {}
  data = {}

  flat_body = {}
  if body_expires_in is not None:
    flat_body["expires_in"] = body_expires_in
  if body_id is not None:
    flat_body["id"] = body_id
  if body_name is not None:
    flat_body["name"] = body_name
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/account/{path_name}/token", method="POST", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
