# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/clusters/{id.value} operations"""

import logging
from typing import Dict, Any, List
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_clust_svc_get(path_id_value: str, param_server: str = None, param_name: str = None, param_id_type: str = None) -> Any:
  """
  Get returns a cluster by server address

  OpenAPI Description:


  Args:

      path_id_value (str): value holds the cluster server URL or cluster name

      param_server (str): OpenAPI parameter corresponding to 'param_server'

      param_name (str): OpenAPI parameter corresponding to 'param_name'

      param_id_type (str): type is the type of the specified cluster identifier ( "server" - default, "name" ).


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/clusters/{id.value}")

  params = {}
  data = {}

  if param_server is not None:
    params["server"] = str(param_server).lower() if isinstance(param_server, bool) else param_server

  if param_name is not None:
    params["name"] = str(param_name).lower() if isinstance(param_name, bool) else param_name

  if param_id_type is not None:
    params["id_type"] = str(param_id_type).lower() if isinstance(param_id_type, bool) else param_id_type

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/clusters/{path_id_value}", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response


async def put_clust_svc_upd(
  path_id_value: str, body: Dict[str, Any] = None, param_updated_fields: List[str] = None, param_id_type: str = None
) -> Any:
  """
  Update updates a cluster

  OpenAPI Description:


  Args:

      path_id_value (str): value holds the cluster server URL or cluster name

      body (Dict[str, Any]): Request body as dictionary. Contains 13 nested properties. See OpenAPI schema for detailed structure.

      param_updated_fields (List[str]): OpenAPI parameter corresponding to 'param_updated_fields'

      param_id_type (str): type is the type of the specified cluster identifier ( "server" - default, "name" ).


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making PUT request to /api/v1/clusters/{id.value}")

  params = {}
  data = {}

  if param_updated_fields is not None:
    params["updated_fields"] = str(param_updated_fields).lower() if isinstance(param_updated_fields, bool) else param_updated_fields

  if param_id_type is not None:
    params["id_type"] = str(param_id_type).lower() if isinstance(param_id_type, bool) else param_id_type

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/clusters/{path_id_value}", method="PUT", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response


async def del_clust_svc_del(path_id_value: str, param_server: str = None, param_name: str = None, param_id_type: str = None) -> Any:
  """
  Delete deletes a cluster

  OpenAPI Description:


  Args:

      path_id_value (str): value holds the cluster server URL or cluster name

      param_server (str): OpenAPI parameter corresponding to 'param_server'

      param_name (str): OpenAPI parameter corresponding to 'param_name'

      param_id_type (str): type is the type of the specified cluster identifier ( "server" - default, "name" ).


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making DELETE request to /api/v1/clusters/{id.value}")

  params = {}
  data = {}

  if param_server is not None:
    params["server"] = str(param_server).lower() if isinstance(param_server, bool) else param_server

  if param_name is not None:
    params["name"] = str(param_name).lower() if isinstance(param_name, bool) else param_name

  if param_id_type is not None:
    params["id_type"] = str(param_id_type).lower() if isinstance(param_id_type, bool) else param_id_type

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/clusters/{path_id_value}", method="DELETE", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
