# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/repocreds operations"""

import logging
from typing import Dict, Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_repo_creds_credentials(param_url: str = None) -> Any:
  """
  ListRepositoryCredentials gets a list of all configured repository credential sets

  OpenAPI Description:


  Args:

      param_url (str): Repo URL for query.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/repocreds")

  params = {}
  data = {}

  if param_url is not None:
    params["url"] = str(param_url).lower() if isinstance(param_url, bool) else param_url

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/api/v1/repocreds", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response


async def post_repo_creds_credentials(body: Dict[str, Any] = None, param_upsert: bool = False) -> Any:
  """
  CreateRepositoryCredentials creates a new repository credential set

  OpenAPI Description:


  Args:

      body (Dict[str, Any]): Request body as dictionary. Contains 19 nested properties. See OpenAPI schema for detailed structure.

      param_upsert (bool): Whether to create in upsert mode.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/repocreds")

  params = {}
  data = {}

  if param_upsert is not None:
    params["upsert"] = str(param_upsert).lower() if isinstance(param_upsert, bool) else param_upsert

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/api/v1/repocreds", method="POST", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
