# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{appName}/server-side-diff operations"""

import logging
from typing import Any, List
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_application_svc_diff(
  path_appName: str, param_app_namespace: str = None, param_project: str = None, param_target_manifests: List[str] = None
) -> Any:
  """
  ServerSideDiff performs server-side diff calculation using dry-run apply

  OpenAPI Description:


  Args:

      path_appName (str): OpenAPI parameter corresponding to 'path_appName'

      param_app_namespace (str): OpenAPI parameter corresponding to 'param_app_namespace'

      param_project (str): OpenAPI parameter corresponding to 'param_project'

      param_target_manifests (List[str]): OpenAPI parameter corresponding to 'param_target_manifests'


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/applications/{appName}/server-side-diff")

  params = {}
  data = {}

  if param_app_namespace is not None:
    params["app_namespace"] = str(param_app_namespace).lower() if isinstance(param_app_namespace, bool) else param_app_namespace

  if param_project is not None:
    params["project"] = str(param_project).lower() if isinstance(param_project, bool) else param_project

  if param_target_manifests is not None:
    params["target_manifests"] = str(param_target_manifests).lower() if isinstance(param_target_manifests, bool) else param_target_manifests

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(
    f"/api/v1/applications/{path_appName}/server-side-diff", method="GET", params=params, data=data
  )

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
