# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/repositories operations"""

import logging
from typing import Dict, Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_repository_svc_ls_repositories(
  param_repo: str = None, param_force_refresh: bool = False, param_app_project: str = None
) -> Any:
  """
  ListRepositories gets a list of all configured repositories

  OpenAPI Description:


  Args:

      param_repo (str): Repo URL for query.

      param_force_refresh (bool): Whether to force a cache refresh on repo's connection state.

      param_app_project (str): App project for query.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/repositories")

  params = {}
  data = {}

  if param_repo is not None:
    params["repo"] = str(param_repo).lower() if isinstance(param_repo, bool) else param_repo

  if param_force_refresh is not None:
    params["force_refresh"] = str(param_force_refresh).lower() if isinstance(param_force_refresh, bool) else param_force_refresh

  if param_app_project is not None:
    params["app_project"] = str(param_app_project).lower() if isinstance(param_app_project, bool) else param_app_project

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/api/v1/repositories", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response


async def post_repository_svc_new_repository(
  body: Dict[str, Any] = None, param_upsert: bool = False, param_creds_only: bool = False
) -> Any:
  """
  CreateRepository creates a new repository configuration

  OpenAPI Description:


  Args:

      body (Dict[str, Any]): Request body as dictionary. Contains 26 nested properties. See OpenAPI schema for detailed structure.

      param_upsert (bool): Whether to create in upsert mode.

      param_creds_only (bool): Whether to operate on credential set instead of repository.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/repositories")

  params = {}
  data = {}

  if param_upsert is not None:
    params["upsert"] = str(param_upsert).lower() if isinstance(param_upsert, bool) else param_upsert

  if param_creds_only is not None:
    params["creds_only"] = str(param_creds_only).lower() if isinstance(param_creds_only, bool) else param_creds_only

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/api/v1/repositories", method="POST", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
