# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/repositories/{repo.repo} operations"""

import logging
from typing import Dict, Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def put_repository_svc_upd_repository(path_repo_repo: str, body: Dict[str, Any] = None) -> Any:
  """
  UpdateRepository updates a repository configuration

  OpenAPI Description:


  Args:

      path_repo_repo (str): Repo contains the URL to the remote repository

      body (Dict[str, Any]): Request body as dictionary. Contains 26 nested properties. See OpenAPI schema for detailed structure.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making PUT request to /api/v1/repositories/{repo.repo}")

  params = {}
  data = {}

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/repositories/{path_repo_repo}", method="PUT", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
