# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{name}/manifests operations"""

import logging
from typing import Any, List
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_application_svc_get_manifests(
  path_name: str,
  param_revision: str = None,
  param_app_namespace: str = None,
  param_project: str = None,
  param_source_positions: List[str] = None,
  param_revisions: List[str] = None,
  param_no_cache: bool = False,
) -> Any:
  """
  GetManifests returns application manifests

  OpenAPI Description:


  Args:

      path_name (str): OpenAPI parameter corresponding to 'path_name'

      param_revision (str): OpenAPI parameter corresponding to 'param_revision'

      param_app_namespace (str): OpenAPI parameter corresponding to 'param_app_namespace'

      param_project (str): OpenAPI parameter corresponding to 'param_project'

      param_source_positions (List[str]): OpenAPI parameter corresponding to 'param_source_positions'

      param_revisions (List[str]): OpenAPI parameter corresponding to 'param_revisions'

      param_no_cache (bool): OpenAPI parameter corresponding to 'param_no_cache'


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/applications/{name}/manifests")

  params = {}
  data = {}

  if param_revision is not None:
    params["revision"] = str(param_revision).lower() if isinstance(param_revision, bool) else param_revision

  if param_app_namespace is not None:
    params["app_namespace"] = str(param_app_namespace).lower() if isinstance(param_app_namespace, bool) else param_app_namespace

  if param_project is not None:
    params["project"] = str(param_project).lower() if isinstance(param_project, bool) else param_project

  if param_source_positions is not None:
    params["source_positions"] = str(param_source_positions).lower() if isinstance(param_source_positions, bool) else param_source_positions

  if param_revisions is not None:
    params["revisions"] = str(param_revisions).lower() if isinstance(param_revisions, bool) else param_revisions

  if param_no_cache is not None:
    params["no_cache"] = str(param_no_cache).lower() if isinstance(param_no_cache, bool) else param_no_cache

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/applications/{path_name}/manifests", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
