# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{name}/rollback operations"""

import logging
from typing import Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def post_application_svc_rollback(
  path_name: str,
  body_app_namespace: str = None,
  body_dry_run: bool = None,
  body_id: int = None,
  body_name: str = None,
  body_project: str = None,
  body_prune: bool = None,
) -> Any:
  """
  Rollback syncs an application to its target state

  OpenAPI Description:


  Args:

      path_name (str): OpenAPI parameter corresponding to 'path_name'

      body_app_namespace (str): OpenAPI parameter corresponding to 'body_app_namespace'

      body_dry_run (bool): OpenAPI parameter corresponding to 'body_dry_run'

      body_id (int): OpenAPI parameter corresponding to 'body_id'

      body_name (str): OpenAPI parameter corresponding to 'body_name'

      body_project (str): OpenAPI parameter corresponding to 'body_project'

      body_prune (bool): OpenAPI parameter corresponding to 'body_prune'


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/applications/{name}/rollback")

  params = {}
  data = {}

  flat_body = {}
  if body_app_namespace is not None:
    flat_body["app_namespace"] = body_app_namespace
  if body_dry_run is not None:
    flat_body["dry_run"] = body_dry_run
  if body_id is not None:
    flat_body["id"] = body_id
  if body_name is not None:
    flat_body["name"] = body_name
  if body_project is not None:
    flat_body["project"] = body_project
  if body_prune is not None:
    flat_body["prune"] = body_prune
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/applications/{path_name}/rollback", method="POST", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
