# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/repositories/{source.repoURL}/appdetails operations"""

import logging
from typing import Dict, Any, List
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def post_repository_svc_get_app_details(
  path_source_repoURL: str,
  body_app_name: str = None,
  body_app_project: str = None,
  body_source_chart: str = None,
  body_source_directory_exclude: str = None,
  body_source_directory_include: str = None,
  body_source_directory_jsonnet_ext_vars: List[Dict[str, Any]] = None,
  body_source_directory_jsonnet_libs: List[str] = None,
  body_source_directory_jsonnet_tlas: List[Dict[str, Any]] = None,
  body_source_directory_recurse: bool = None,
  body_source_helm: Dict[str, Any] = None,
  body_source_kustomize: Dict[str, Any] = None,
  body_source_name: str = None,
  body_source_path: str = None,
  body_source_plugin_env: List[Dict[str, Any]] = None,
  body_source_plugin_name: str = None,
  body_source_plugin_parameters: List[Dict[str, Any]] = None,
  body_source_ref: str = None,
  body_source_repo_url: str = None,
  body_source_target_revision: str = None,
  body_source_index: int = None,
  body_version_id: int = None,
) -> Any:
  """
      GetAppDetails returns application details by given path

      OpenAPI Description:


      Args:

          path_source_repoURL (str): RepoURL is the URL to the repository (Git or Helm) that contains the application manifests

          body_app_name (str): OpenAPI parameter corresponding to 'body_app_name'

          body_app_project (str): OpenAPI parameter corresponding to 'body_app_project'

          body_source_chart (str): Chart is a Helm chart name, and must be specified for applications sourced from a Helm repo.

          body_source_directory_exclude (str): OpenAPI parameter corresponding to 'body_source_directory_exclude'

          body_source_directory_include (str): OpenAPI parameter corresponding to 'body_source_directory_include'

          body_source_directory_jsonnet_ext_vars (List[Dict[str, Any]]): OpenAPI parameter corresponding to 'body_source_directory_jsonnet_ext_vars'

          body_source_directory_jsonnet_libs (List[str]): OpenAPI parameter corresponding to 'body_source_directory_jsonnet_libs'

          body_source_directory_jsonnet_tlas (List[Dict[str, Any]]): OpenAPI parameter corresponding to 'body_source_directory_jsonnet_tlas'

          body_source_directory_recurse (bool): OpenAPI parameter corresponding to 'body_source_directory_recurse'

          body_source_helm (Dict[str, Any]): Request body as dictionary. Contains 15 nested properties. See OpenAPI schema for detailed structure.

          body_source_kustomize (Dict[str, Any]): Request body as dictionary. Contains 18 nested properties. See OpenAPI schema for detailed structure.

          body_source_name (str): Name is used to refer to a source and is displayed in the UI. It is used in multi-source Applications.

          body_source_path (str): Path is a directory path within the Git repository, and is only valid for applications sourced from Git.

          body_source_plugin_env (List[Dict[str, Any]]): OpenAPI parameter corresponding to 'body_source_plugin_env'

          body_source_plugin_name (str): OpenAPI parameter corresponding to 'body_source_plugin_name'

          body_source_plugin_parameters (List[Dict[str, Any]]): OpenAPI parameter corresponding to 'body_source_plugin_parameters'

          body_source_ref (str): Ref is reference to another source within sources field. This field will not be used if used with a `source` tag.

          body_source_repo_url (str): OpenAPI parameter corresponding to 'body_source_repo_url'

          body_source_target_revision (str): TargetRevision defines the revision of the source to sync the application to.
  In case of Git, this can be commit, tag, or branch. If omitted, will equal to HEAD.
  In case of Helm, this is a semver tag for the Chart's version.

          body_source_index (int): OpenAPI parameter corresponding to 'body_source_index'

          body_version_id (int): OpenAPI parameter corresponding to 'body_version_id'


      Returns:
          Any: The JSON response from the API call.

      Raises:
          Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/repositories/{source.repoURL}/appdetails")

  params = {}
  data = {}

  flat_body = {}
  if body_app_name is not None:
    flat_body["app_name"] = body_app_name
  if body_app_project is not None:
    flat_body["app_project"] = body_app_project
  if body_source_chart is not None:
    flat_body["source_chart"] = body_source_chart
  if body_source_directory_exclude is not None:
    flat_body["source_directory_exclude"] = body_source_directory_exclude
  if body_source_directory_include is not None:
    flat_body["source_directory_include"] = body_source_directory_include
  if body_source_directory_jsonnet_ext_vars is not None:
    flat_body["source_directory_jsonnet_ext_vars"] = body_source_directory_jsonnet_ext_vars
  if body_source_directory_jsonnet_libs is not None:
    flat_body["source_directory_jsonnet_libs"] = body_source_directory_jsonnet_libs
  if body_source_directory_jsonnet_tlas is not None:
    flat_body["source_directory_jsonnet_tlas"] = body_source_directory_jsonnet_tlas
  if body_source_directory_recurse is not None:
    flat_body["source_directory_recurse"] = body_source_directory_recurse
  if body_source_helm is not None:
    flat_body["source_helm"] = body_source_helm
  if body_source_kustomize is not None:
    flat_body["source_kustomize"] = body_source_kustomize
  if body_source_name is not None:
    flat_body["source_name"] = body_source_name
  if body_source_path is not None:
    flat_body["source_path"] = body_source_path
  if body_source_plugin_env is not None:
    flat_body["source_plugin_env"] = body_source_plugin_env
  if body_source_plugin_name is not None:
    flat_body["source_plugin_name"] = body_source_plugin_name
  if body_source_plugin_parameters is not None:
    flat_body["source_plugin_parameters"] = body_source_plugin_parameters
  if body_source_ref is not None:
    flat_body["source_ref"] = body_source_ref
  if body_source_repo_url is not None:
    flat_body["source_repo_url"] = body_source_repo_url
  if body_source_target_revision is not None:
    flat_body["source_target_revision"] = body_source_target_revision
  if body_source_index is not None:
    flat_body["source_index"] = body_source_index
  if body_version_id is not None:
    flat_body["version_id"] = body_version_id
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(
    f"/api/v1/repositories/{path_source_repoURL}/appdetails", method="POST", params=params, data=data
  )

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
