[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "agent-make-mcp"
version = "0.1.0"
description = "Tool to generate MCP servers from OpenAPI specifications"
authors = ["Rehan Agrawal <rehagraw@cisco.com>"]
packages = [
    { include = "*.py" },
]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
httpx = "^0.24.0"
python-dotenv = "^1.0.0"
pydantic = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
black = "^23.0"
isort = "^5.0"
flake8 = "^6.0"

[tool.poetry.scripts]
generate-mcp = "generate_mcp:main" 