# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/write-repositories/{repo.repo} operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def repository_service__update_write_repository(path_repo_repo: str) -> Dict[str, Any]:
    '''
    UpdateWriteRepository updates a write repository configuration.

    Args:
        path_repo_repo (str): The URL to the remote repository.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the updated repository configuration.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making PUT request to /api/v1/write-repositories/{repo.repo}")

    params = {}
    data = {}

    success, response = await make_api_request(
        f"/api/v1/write-repositories/{path_repo_repo}", method="PUT", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response