# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{application.metadata.name} operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_service__update(
    path_application_metadata_name: str, param_validate: str = None, param_project: str = None
) -> Dict[str, Any]:
    '''
    Update an application.

    Args:
        path_application_metadata_name (str): The name of the application metadata to update.
        param_validate (str, optional): Validation parameter for the update process. Defaults to None.
        param_project (str, optional): Project parameter for the update process. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the updated application details.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making PUT request to /api/v1/applications/{application.metadata.name}")

    params = {}
    data = {}

    params["validate"] = param_validate
    params["project"] = param_project

    success, response = await make_api_request(
        f"/api/v1/applications/{path_application_metadata_name}", method="PUT", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response