# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/clusters/{id.value}/rotate-auth operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def cluster_service__rotate_auth(path_id_value: str) -> Dict[str, Any]:
    '''
    Rotate the bearer token used for a cluster.

    Args:
        path_id_value (str): The identifier for the cluster whose bearer token is to be rotated.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the status of the token rotation.

    Raises:
        Exception: If the API request fails or returns an error, an exception is raised with the error details.
    '''
    logger.debug("Making POST request to /api/v1/clusters/{id.value}/rotate-auth")

    params = {}
    data = {}

    success, response = await make_api_request(
        f"/api/v1/clusters/{path_id_value}/rotate-auth", method="POST", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response