
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/write-repocreds operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def repocredsservice_listwriterepositorycredentials(url: str = None) -> Dict[str, Any]:
    """
    ListWriteRepositoryCredentials gets a list of all configured repository credential sets that have write access
    """
    logger.debug("Making GET request to /api/v1/write-repocreds")
    params = {}
    data = None

    success, response = await make_api_request(
        "/api/v1/write-repocreds",
        method="GET",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def repocredsservice_createwriterepositorycredentials(body: str, upsert: str = None) -> Dict[str, Any]:
    """
    CreateWriteRepositoryCredentials creates a new repository credential set with write access
    """
    logger.debug("Making POST request to /api/v1/write-repocreds")
    params = {}
    data = None

    # Add parameters to request
    if body is not None:
        data = body

    success, response = await make_api_request(
        "/api/v1/write-repocreds",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response

