
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/write-repositories operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def repositoryservice_listwriterepositories(repo: str = None, forceRefresh: str = None, appProject: str = None) -> Dict[str, Any]:
    '''
    Retrieves a list of all configured write repositories.

    Args:
        repo (str, optional): The name of the repository to filter results. Defaults to None.
        forceRefresh (str, optional): If set, forces a refresh of the repository list. Defaults to None.
        appProject (str, optional): The application project to filter repositories by. Defaults to None.

    Returns:
        Dict[str, Any]: A dictionary containing the list of write repositories or an error message.

    Raises:
        Exception: If the API request fails or returns an unexpected response.

    OpenAPI Specification:
      get:
        summary: List all configured write repositories.
        operationId: listWriteRepositories
        parameters:
          - in: query
            name: repo
            schema:
              type: string
            required: false
            description: The name of the repository to filter results.
          - in: query
            name: forceRefresh
            schema:
              type: string
            required: false
            description: If set, forces a refresh of the repository list.
          - in: query
            name: appProject
            schema:
              type: string
            required: false
            description: The application project to filter repositories by.
        responses:
          '200':
            description: A list of configured write repositories.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    repositories:
                      type: array
                      items:
                        type: object
          '400':
            description: Invalid request parameters.
          '500':
            description: Internal server error.
    '''
    logger.debug("Making GET request to /api/v1/write-repositories")
    params = {}
    data = None

    success, response = await make_api_request(
        "/api/v1/write-repositories",
        method="GET",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def repositoryservice_createwriterepository(body: str, upsert: str = None, credsOnly: str = None) -> Dict[str, Any]:
    '''
    Creates a new write repository configuration.

    Args:
        body (str): The JSON-encoded repository configuration to create.
        upsert (str, optional): If set, allows upserting an existing repository configuration. Defaults to None.
        credsOnly (str, optional): If set, only credentials will be updated. Defaults to None.

    Returns:
        Dict[str, Any]: The response from the API containing the created repository configuration or error details.

    Raises:
        Exception: If the API request fails or returns an error.

    OpenAPI Specification:
      post:
        summary: Create a new write repository configuration.
        operationId: repositoryservice_createwriterepository
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                description: Repository configuration payload.
        parameters:
          - in: query
            name: upsert
            schema:
              type: string
            required: false
            description: If set, allows upserting an existing repository configuration.
          - in: query
            name: credsOnly
            schema:
              type: string
            required: false
            description: If set, only credentials will be updated.
        responses:
          '200':
            description: Successfully created the write repository configuration.
            content:
              application/json:
                schema:
                  type: object
          '400':
            description: Invalid request or payload.
            content:
              application/json:
                schema:
                  type: object
          '500':
            description: Internal server error.
            content:
              application/json:
                schema:
                  type: object
    '''
    logger.debug("Making POST request to /api/v1/write-repositories")
    params = {}
    data = None

    # Add parameters to request
    if body is not None:
        data = body

    success, response = await make_api_request(
        "/api/v1/write-repositories",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response
