# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{name}/revisions/{revision}/chartdetails operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_service__revision_chart_details(
    path_name: str,
    path_revision: str,
    param_appNamespace: str = None,
    param_project: str = None,
    param_sourceIndex: str = None,
    param_versionId: str = None,
) -> Dict[str, Any]:
    """
    Get the chart metadata (description, maintainers, home) for a specific revision of the application

    OpenAPI Description:


    Args:
    path_name (str): OpenAPI parameter corresponding to 'path_name'.
    path_revision (str): OpenAPI parameter corresponding to 'path_revision'.
    param_appNamespace (str = None): OpenAPI parameter corresponding to 'param_appNamespace'.
    param_project (str = None): OpenAPI parameter corresponding to 'param_project'.
    param_sourceIndex (str = None): OpenAPI parameter corresponding to 'param_sourceIndex'.
    param_versionId (str = None): OpenAPI parameter corresponding to 'param_versionId'.


    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/applications/{name}/revisions/{revision}/chartdetails")

    params = {}
    data = {}

    params["appNamespace"] = param_appNamespace
    params["project"] = param_project
    params["sourceIndex"] = param_sourceIndex
    params["versionId"] = param_versionId

    success, response = await make_api_request(
        f"/api/v1/applications/{path_name}/revisions/{path_revision}/chartdetails",
        method="GET",
        params=params,
        data=data,
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
