# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/projects/{name}/globalprojects operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def project_service__get_global_projects(path_name: str) -> Dict[str, Any]:
    '''
    Get a virtual project by name.

    Args:
        path_name (str): The name of the virtual project to retrieve.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the project details.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/projects/{name}/globalprojects")

    params = {}
    data = {}

    success, response = await make_api_request(
        f"/api/v1/projects/{path_name}/globalprojects", method="GET", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response