
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/write-repocreds operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def repocredsservice_listwriterepositorycredentials(url: str = None) -> Dict[str, Any]:
    '''
    Retrieves a list of all configured repository credential sets with write access.

    Args:
        url (str, optional): The base URL of the API endpoint. Defaults to None.

    Returns:
        Dict[str, Any]: A dictionary containing the list of repository credential sets with write access, or an error message.

    Raises:
        Exception: If the API request fails or an unexpected error occurs.

    OpenAPI Specification:
      get:
        summary: List repository credentials with write access
        description: Retrieves all configured repository credential sets that have write access.
        operationId: listWriteRepositoryCredentials
        tags:
          - RepositoryCredentials
        parameters: []
        responses:
          '200':
            description: A list of repository credential sets with write access.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    credentials:
                      type: array
                      items:
                        type: object
          '400':
            description: Bad request.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
          '500':
            description: Internal server error.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
    '''
    logger.debug("Making GET request to /api/v1/write-repocreds")
    params = {}
    data = None

    success, response = await make_api_request(
        "/api/v1/write-repocreds",
        method="GET",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def repocredsservice_createwriterepositorycredentials(body: str, upsert: str = None) -> Dict[str, Any]:
    '''
    Creates a new repository credential set with write access.

    Args:
        body (str): The JSON-encoded request body containing repository credential details.
        upsert (str, optional): If set, allows updating existing credentials. Defaults to None.

    Returns:
        Dict[str, Any]: The API response containing the created or updated repository credentials.

    Raises:
        Exception: If the API request fails or returns an error.

    OpenAPI Specification:
      post:
        summary: Create a new repository credential set with write access.
        operationId: repocredsservice_createwriterepositorycredentials
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                description: Repository credential details.
        parameters:
          - in: query
            name: upsert
            schema:
              type: string
            required: false
            description: If set, allows updating existing credentials.
        responses:
          '200':
            description: Successfully created or updated repository credentials.
            content:
              application/json:
                schema:
                  type: object
          '400':
            description: Invalid request or missing required fields.
          '500':
            description: Internal server error.
    '''
    logger.debug("Making POST request to /api/v1/write-repocreds")
    params = {}
    data = None

    # Add parameters to request
    if body is not None:
        data = body

    success, response = await make_api_request(
        "/api/v1/write-repocreds",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response
