# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/account/{name}/token operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def account_service__create_token(path_name: str) -> Dict[str, Any]:
    '''
    Create a token for the specified account.

    Args:
        path_name (str): The name of the account for which the token is to be created.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the token details.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making POST request to /api/v1/account/{name}/token")

    params = {}
    data = {}

    success, response = await make_api_request(
        f"/api/v1/account/{path_name}/token", method="POST", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response