# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/account operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def account_service__list_accounts() -> Dict[str, Any]:
    '''
    List accounts from the account service.

    This function makes an asynchronous GET request to the account service API to retrieve a list of accounts.

    Args:
        None

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the list of accounts. If the request fails, returns a dictionary with an error message.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/account")

    params = {}
    data = {}

    success, response = await make_api_request("/api/v1/account", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response