# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/repositories/{repo}/helmcharts operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def repository_service__get_helm_charts(
    path_repo: str, param_forceRefresh: str = None, param_appProject: str = None
) -> Dict[str, Any]:
    '''
    Get a list of Helm charts in the specified repository.

    Args:
        path_repo (str): The path to the repository from which to retrieve Helm charts.
        param_forceRefresh (str, optional): A parameter to force refresh the data. Defaults to None.
        param_appProject (str, optional): The application project parameter. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the list of Helm charts.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/repositories/{repo}/helmcharts")

    params = {}
    data = {}

    params["forceRefresh"] = param_forceRefresh
    params["appProject"] = param_appProject

    success, response = await make_api_request(
        f"/api/v1/repositories/{path_repo}/helmcharts", method="GET", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response