# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/stream/sensors/{namespace}/logs operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_sns_svc_snss_logs(
  path_namespace: str,
  param_name: str = None,
  param_trigger_name: str = None,
  param_grep: str = None,
  param_pod_log_options_container: str = None,
  param_pod_log_options_follow: bool = False,
  param_pod_log_options_previous: bool = False,
  param_pod_log_options_since_seconds: str = None,
  param_pod_log_options_since_time_seconds: str = None,
  param_pod_log_options_since_time_nanos: int = None,
  param_pod_log_options_timestamps: bool = False,
  param_pod_log_options_tail_lines: str = None,
  param_pod_log_options_limit_bytes: str = None,
  param_pod_log_options_insecure_skip_tls_verify_backend: bool = False,
  param_pod_log_options_stream: str = None,
) -> Any:
  """


      OpenAPI Description:


      Args:

          path_namespace (str): OpenAPI parameter corresponding to 'path_namespace'

          param_name (str): optional - only return entries for this sensor name.

          param_trigger_name (str): optional - only return entries for this trigger.

          param_grep (str): option - only return entries where `msg` contains this regular expressions.

          param_pod_log_options_container (str): The container for which to stream logs. Defaults to only container if there is one container in the pod.
  +optional.

          param_pod_log_options_follow (bool): Follow the log stream of the pod. Defaults to false.
  +optional.

          param_pod_log_options_previous (bool): Return previous terminated container logs. Defaults to false.
  +optional.

          param_pod_log_options_since_seconds (str): A relative time in seconds before the current time from which to show logs. If this value
  precedes the time a pod was started, only logs since the pod start will be returned.
  If this value is in the future, no logs will be returned.
  Only one of sinceSeconds or sinceTime may be specified.
  +optional.

          param_pod_log_options_since_time_seconds (str): Represents seconds of UTC time since Unix epoch
  1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
  9999-12-31T23:59:59Z inclusive.

          param_pod_log_options_since_time_nanos (int): Non-negative fractions of a second at nanosecond resolution. Negative
  second values with fractions must still have non-negative nanos values
  that count forward in time. Must be from 0 to 999,999,999
  inclusive. This field may be limited in precision depending on context.

          param_pod_log_options_timestamps (bool): If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line
  of log output. Defaults to false.
  +optional.

          param_pod_log_options_tail_lines (str): If set, the number of lines from the end of the logs to show. If not specified,
  logs are shown from the creation of the container or sinceSeconds or sinceTime.
  Note that when "TailLines" is specified, "Stream" can only be set to nil or "All".
  +optional.

          param_pod_log_options_limit_bytes (str): If set, the number of bytes to read from the server before terminating the
  log output. This may not display a complete final line of logging, and may return
  slightly more or slightly less than the specified limit.
  +optional.

          param_pod_log_options_insecure_skip_tls_verify_backend (bool): insecureSkipTLSVerifyBackend indicates that the apiserver should not confirm the validity of the
  serving certificate of the backend it is connecting to.  This will make the HTTPS connection between the apiserver
  and the backend insecure. This means the apiserver cannot verify the log data it is receiving came from the real
  kubelet.  If the kubelet is configured to verify the apiserver's TLS credentials, it does not mean the
  connection to the real kubelet is vulnerable to a man in the middle attack (e.g. an attacker could not intercept
  the actual log data coming from the real kubelet).
  +optional.

          param_pod_log_options_stream (str): Specify which container log stream to return to the client.
  Acceptable values are "All", "Stdout" and "Stderr". If not specified, "All" is used, and both stdout and stderr
  are returned interleaved.
  Note that when "TailLines" is specified, "Stream" can only be set to nil or "All".
  +featureGate=PodLogsQuerySplitStreams
  +optional.


      Returns:
          Any: The JSON response from the API call.

      Raises:
          Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/stream/sensors/{namespace}/logs")

  params = {}
  data = {}

  if param_name is not None:
    params["name"] = str(param_name).lower() if isinstance(param_name, bool) else param_name

  if param_trigger_name is not None:
    params["trigger_name"] = str(param_trigger_name).lower() if isinstance(param_trigger_name, bool) else param_trigger_name

  if param_grep is not None:
    params["grep"] = str(param_grep).lower() if isinstance(param_grep, bool) else param_grep

  if param_pod_log_options_container is not None:
    params["pod_log_options_container"] = (
      str(param_pod_log_options_container).lower() if isinstance(param_pod_log_options_container, bool) else param_pod_log_options_container
    )

  if param_pod_log_options_follow is not None:
    params["pod_log_options_follow"] = (
      str(param_pod_log_options_follow).lower() if isinstance(param_pod_log_options_follow, bool) else param_pod_log_options_follow
    )

  if param_pod_log_options_previous is not None:
    params["pod_log_options_previous"] = (
      str(param_pod_log_options_previous).lower() if isinstance(param_pod_log_options_previous, bool) else param_pod_log_options_previous
    )

  if param_pod_log_options_since_seconds is not None:
    params["pod_log_options_since_seconds"] = (
      str(param_pod_log_options_since_seconds).lower()
      if isinstance(param_pod_log_options_since_seconds, bool)
      else param_pod_log_options_since_seconds
    )

  if param_pod_log_options_since_time_seconds is not None:
    params["pod_log_options_since_time_seconds"] = (
      str(param_pod_log_options_since_time_seconds).lower()
      if isinstance(param_pod_log_options_since_time_seconds, bool)
      else param_pod_log_options_since_time_seconds
    )

  if param_pod_log_options_since_time_nanos is not None:
    params["pod_log_options_since_time_nanos"] = (
      str(param_pod_log_options_since_time_nanos).lower()
      if isinstance(param_pod_log_options_since_time_nanos, bool)
      else param_pod_log_options_since_time_nanos
    )

  if param_pod_log_options_timestamps is not None:
    params["pod_log_options_timestamps"] = (
      str(param_pod_log_options_timestamps).lower()
      if isinstance(param_pod_log_options_timestamps, bool)
      else param_pod_log_options_timestamps
    )

  if param_pod_log_options_tail_lines is not None:
    params["pod_log_options_tail_lines"] = (
      str(param_pod_log_options_tail_lines).lower()
      if isinstance(param_pod_log_options_tail_lines, bool)
      else param_pod_log_options_tail_lines
    )

  if param_pod_log_options_limit_bytes is not None:
    params["pod_log_options_limit_bytes"] = (
      str(param_pod_log_options_limit_bytes).lower()
      if isinstance(param_pod_log_options_limit_bytes, bool)
      else param_pod_log_options_limit_bytes
    )

  if param_pod_log_options_insecure_skip_tls_verify_backend is not None:
    params["pod_log_options_insecure_skip_tls_verify_backend"] = (
      str(param_pod_log_options_insecure_skip_tls_verify_backend).lower()
      if isinstance(param_pod_log_options_insecure_skip_tls_verify_backend, bool)
      else param_pod_log_options_insecure_skip_tls_verify_backend
    )

  if param_pod_log_options_stream is not None:
    params["pod_log_options_stream"] = (
      str(param_pod_log_options_stream).lower() if isinstance(param_pod_log_options_stream, bool) else param_pod_log_options_stream
    )

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/stream/sensors/{path_namespace}/logs", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
