# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/cluster-workflow-templates/lint operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def post_clust_wf_tpl(
  body_create_options_dry_run: List[str] = None,
  body_create_options_field_manager: str = None,
  body_create_options_field_validation: str = None,
  body_template_api_version: str = None,
  body_template_kind: str = None,
  body_template_metadata: Dict[str, Any] = None,
  body_template_spec: Dict[str, Any] = None,
) -> Any:
  """


  OpenAPI Description:


  Args:

      body_create_options_dry_run (List[str]): OpenAPI parameter corresponding to 'body_create_options_dry_run'

      body_create_options_field_manager (str): OpenAPI parameter corresponding to 'body_create_options_field_manager'

      body_create_options_field_validation (str): OpenAPI parameter corresponding to 'body_create_options_field_validation'

      body_template_api_version (str): APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources

      body_template_kind (str): Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

      body_template_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

      body_template_spec (Dict[str, Any]): WorkflowSpec is the specification of a Workflow.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/cluster-workflow-templates/lint")

  params = {}
  data = {}

  flat_body = {}
  if body_create_options_dry_run is not None:
    flat_body["create_options_dry_run"] = body_create_options_dry_run
  if body_create_options_field_manager is not None:
    flat_body["create_options_field_manager"] = body_create_options_field_manager
  if body_create_options_field_validation is not None:
    flat_body["create_options_field_validation"] = body_create_options_field_validation
  if body_template_api_version is not None:
    flat_body["template_api_version"] = body_template_api_version
  if body_template_kind is not None:
    flat_body["template_kind"] = body_template_kind
  if body_template_metadata is not None:
    flat_body["template_metadata"] = body_template_metadata
  if body_template_spec is not None:
    flat_body["template_spec"] = body_template_spec
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/api/v1/cluster-workflow-templates/lint", method="POST", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
