# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName} operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_art_svc_get_art_file(
  path_namespace: str, path_idDiscriminator: str, path_id: str, path_nodeId: str, path_artifactName: str, path_artifactDiscriminator: str
) -> Any:
  """
  Get an artifact.

  OpenAPI Description:


  Args:

      path_namespace (str): OpenAPI parameter corresponding to 'path_namespace'

      path_idDiscriminator (str): OpenAPI parameter corresponding to 'path_idDiscriminator'

      path_id (str): OpenAPI parameter corresponding to 'path_id'

      path_nodeId (str): OpenAPI parameter corresponding to 'path_nodeId'

      path_artifactName (str): OpenAPI parameter corresponding to 'path_artifactName'

      path_artifactDiscriminator (str): OpenAPI parameter corresponding to 'path_artifactDiscriminator'


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}")

  params = {}
  data = {}

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(
    f"/artifact-files/{path_namespace}/{path_idDiscriminator}/{path_id}/{path_nodeId}/{path_artifactDiscriminator}/{path_artifactName}",
    method="GET",
    params=params,
    data=data,
  )

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
