# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /alertmuting/{id} operations"""

import logging
from typing import Any, List
from mcp_splunk.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def retrieve__muting__rule_id(path_id: str) -> Any:
    '''
    Retrieves the muting rule specified by the given muting rule ID.

    Args:
        path_id (str): The ID of the muting rule to retrieve.

    Returns:
        Any: The JSON response containing the details of the specified muting rule.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /alertmuting/{id}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/alertmuting/{path_id}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def update__single__muting__rule(
    path_id: str,
    param_resolveMatchingActiveAlerts: bool = False,
    body_created: int = None,
    body_creator: str = None,
    body_description: str = None,
    body_filters: List[str] = None,
    body_id: str = None,
    body_lastUpdated: int = None,
    body_lastUpdatedBy: str = None,
    body_recurrence_unit: str = None,
    body_recurrence_value: int = None,
    body_linkedTeams: List[str] = None,
    body_sendAlertsOnceMutingPeriodHasEnded: bool = None,
    body_startTime: int = None,
    body_stopTime: int = None,
) -> Any:
    '''
    Updates a muting rule in Splunk Observability Cloud.

    Args:
        path_id (str): ID of the muting rule you want to modify.
        param_resolveMatchingActiveAlerts (bool, optional): Indicates whether to resolve matching active alerts for the rule. Defaults to False.
        body_created (int, optional): Detector creation timestamp in Unix time (milliseconds). Set by system. Defaults to None.
        body_creator (str, optional): ID of the user who created the detector. Set by system. Defaults to None.
        body_description (str, optional): Description of the muting rule. Defaults to None.
        body_filters (List[str], optional): List of muting filters for this rule. Defaults to None.
        body_id (str, optional): Detector ID. Set by system. Defaults to None.
        body_lastUpdated (int, optional): Detector last updated timestamp in Unix time (milliseconds). Set by system. Defaults to None.
        body_lastUpdatedBy (str, optional): ID of the user who last updated the detector. Defaults to None.
        body_recurrence_unit (str, optional): Unit of the recurrence period. Can be days ('d') or weeks ('w'). Defaults to None.
        body_recurrence_value (int, optional): Amount of time, expressed as an integer applicable to the unit. Defaults to None.
        body_linkedTeams (List[str], optional): IDs of teams linked to the detector that created the incident. This property is read-only and always set by the system. Defaults to None.
        body_sendAlertsOnceMutingPeriodHasEnded (bool, optional): Controls notifications after the muting period ends. Defaults to None.
        body_startTime (int, optional): Starting timestamp of the muting rule in Unix time (milliseconds). Defaults to None.
        body_stopTime (int, optional): Ending timestamp of the muting rule in Unix time (milliseconds). Defaults to None.

    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making PUT request to /alertmuting/{id}")

    params = {}
    data = {}

    if param_resolveMatchingActiveAlerts is not None:
        params["resolveMatchingActiveAlerts"] = (
            str(param_resolveMatchingActiveAlerts).lower()
            if isinstance(param_resolveMatchingActiveAlerts, bool)
            else param_resolveMatchingActiveAlerts
        )

    flat_body = {}
    if body_created is not None:
        flat_body["created"] = body_created
    if body_creator is not None:
        flat_body["creator"] = body_creator
    if body_description is not None:
        flat_body["description"] = body_description
    if body_filters is not None:
        flat_body["filters"] = body_filters
    if body_id is not None:
        flat_body["id"] = body_id
    if body_lastUpdated is not None:
        flat_body["lastUpdated"] = body_lastUpdated
    if body_lastUpdatedBy is not None:
        flat_body["lastUpdatedBy"] = body_lastUpdatedBy
    if body_recurrence_unit is not None:
        flat_body["recurrence_unit"] = body_recurrence_unit
    if body_recurrence_value is not None:
        flat_body["recurrence_value"] = body_recurrence_value
    if body_linkedTeams is not None:
        flat_body["linkedTeams"] = body_linkedTeams
    if body_sendAlertsOnceMutingPeriodHasEnded is not None:
        flat_body["sendAlertsOnceMutingPeriodHasEnded"] = body_sendAlertsOnceMutingPeriodHasEnded
    if body_startTime is not None:
        flat_body["startTime"] = body_startTime
    if body_stopTime is not None:
        flat_body["stopTime"] = body_stopTime
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/alertmuting/{path_id}", method="PUT", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def delete__single__muting__rule(path_id: str) -> Any:
    '''
    Deletes a muting rule specified by the given ID.

    Args:
        path_id (str): The ID of the muting rule to delete.

    Returns:
        Any: The JSON response from the API call indicating the result of the delete operation.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making DELETE request to /alertmuting/{id}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/alertmuting/{path_id}", method="DELETE", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response