# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /detector/{id}/incidents operations"""

import logging
from typing import Any
from mcp_splunk.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def retrieve__incidents__single__detector(path_id: str, param_offset: int = None, param_limit: int = None) -> Any:
    '''
    Retrieves the active incidents for a specific detector.

    Args:
        path_id (str): ID of the detector that generated the incidents.
        param_offset (int, optional): Index in the result set at which to start receiving results. Defaults to None.
        param_limit (int, optional): Number of results to return. Defaults to None.

    Returns:
        Any: The JSON response from the API call containing the list of active incidents for the specified detector.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /detector/{id}/incidents")

    params = {}
    data = {}

    if param_offset is not None:
        params["offset"] = str(param_offset).lower() if isinstance(param_offset, bool) else param_offset

    if param_limit is not None:
        params["limit"] = str(param_limit).lower() if isinstance(param_limit, bool) else param_limit

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/detector/{path_id}/incidents", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response