# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

#!/usr/bin/env python3
"""
 MCP Server

This server provides a Model Context Protocol (MCP) interface to the ,
allowing large language models and AI assistants to interact with the service.
"""

import logging
import os
from dotenv import load_dotenv
from fastmcp import FastMCP


from mcp_argo_workflows.tools import api_v1_archived_workflows

from mcp_argo_workflows.tools import api_v1_archived_workflows_label_keys

from mcp_argo_workflows.tools import api_v1_archived_workflows_label_values

from mcp_argo_workflows.tools import api_v1_archived_workflows_uid

from mcp_argo_workflows.tools import api_v1_archived_workflows_uid_resubmit

from mcp_argo_workflows.tools import api_v1_archived_workflows_uid_retry

from mcp_argo_workflows.tools import api_v1_cluster_workflow_templates

from mcp_argo_workflows.tools import api_v1_cluster_workflow_templates_lint

from mcp_argo_workflows.tools import api_v1_cluster_workflow_templates_name

from mcp_argo_workflows.tools import api_v1_cron_workflows_namespace

from mcp_argo_workflows.tools import api_v1_cron_workflows_namespace_lint

from mcp_argo_workflows.tools import api_v1_cron_workflows_namespace_name

from mcp_argo_workflows.tools import api_v1_cron_workflows_namespace_name_resume

from mcp_argo_workflows.tools import api_v1_cron_workflows_namespace_name_suspend

from mcp_argo_workflows.tools import api_v1_event_sources_namespace

from mcp_argo_workflows.tools import api_v1_event_sources_namespace_name

from mcp_argo_workflows.tools import api_v1_events_namespace_discriminator

from mcp_argo_workflows.tools import api_v1_info

from mcp_argo_workflows.tools import api_v1_sensors_namespace

from mcp_argo_workflows.tools import api_v1_sensors_namespace_name

from mcp_argo_workflows.tools import api_v1_stream_event_sources_namespace

from mcp_argo_workflows.tools import api_v1_stream_event_sources_namespace_logs

from mcp_argo_workflows.tools import api_v1_stream_events_namespace

from mcp_argo_workflows.tools import api_v1_stream_sensors_namespace

from mcp_argo_workflows.tools import api_v1_stream_sensors_namespace_logs

from mcp_argo_workflows.tools import api_v1_tracking_event

from mcp_argo_workflows.tools import api_v1_userinfo

from mcp_argo_workflows.tools import api_v1_version

from mcp_argo_workflows.tools import api_v1_workflow_event_bindings_namespace

from mcp_argo_workflows.tools import api_v1_workflow_events_namespace

from mcp_argo_workflows.tools import api_v1_workflow_templates_namespace

from mcp_argo_workflows.tools import api_v1_workflow_templates_namespace_lint

from mcp_argo_workflows.tools import api_v1_workflow_templates_namespace_name

from mcp_argo_workflows.tools import api_v1_workflows_namespace

from mcp_argo_workflows.tools import api_v1_workflows_namespace_lint

from mcp_argo_workflows.tools import api_v1_workflows_namespace_submit

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_log

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_resubmit

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_resume

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_retry

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_set

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_stop

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_suspend

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_terminate

from mcp_argo_workflows.tools import api_v1_workflows_namespace_name_podname_log

from mcp_argo_workflows.tools import artifact_files_namespace_iddiscriminator_id_nodeid_artifactdiscriminator_artifactname

from mcp_argo_workflows.tools import artifacts_by_uid_uid_nodeid_artifactname

from mcp_argo_workflows.tools import artifacts_namespace_name_nodeid_artifactname

from mcp_argo_workflows.tools import input_artifacts_by_uid_uid_nodeid_artifactname

from mcp_argo_workflows.tools import input_artifacts_namespace_name_nodeid_artifactname


def main():
  # Load environment variables
  load_dotenv()

  # Configure logging
  logging.basicConfig(level=logging.INFO)

  # Get MCP configuration from environment variables
  MCP_MODE = os.getenv("MCP_MODE", "stdio").lower()

  # Get host and port for server
  MCP_HOST = os.getenv("MCP_HOST", "localhost")
  MCP_PORT = int(os.getenv("MCP_PORT", "8000"))

  logging.info(f"Starting MCP server in {MCP_MODE} mode on {MCP_HOST}:{MCP_PORT}")

  # Get agent name from environment variables
  SERVER_NAME = os.getenv("SERVER_NAME") or os.getenv("AGENT_NAME") or "ARGO_WORKFLOWS"
  logging.info(f"MCP Server name: {SERVER_NAME}")

  # Create server instance
  if MCP_MODE.lower() in ["sse", "http"]:
    mcp = FastMCP(f"{SERVER_NAME} MCP Server", host=MCP_HOST, port=MCP_PORT)
  else:
    mcp = FastMCP(f"{SERVER_NAME} MCP Server")

  # Register api_v1_archived_workflows tools

  mcp.tool()(api_v1_archived_workflows.get_arch_wf_svc_ls_arch_wfs)

  # Register api_v1_archived_workflows_label_keys tools

  mcp.tool()(api_v1_archived_workflows_label_keys.get_arch_wf_keys)

  # Register api_v1_archived_workflows_label_values tools

  mcp.tool()(api_v1_archived_workflows_label_values.get_arch_wf_values)

  # Register api_v1_archived_workflows_uid tools

  mcp.tool()(api_v1_archived_workflows_uid.get_arch_wf_svc_get_arch_wf)

  mcp.tool()(api_v1_archived_workflows_uid.del_arch_wf_svc_del_arch_wf)

  # Register api_v1_archived_workflows_uid_resubmit tools

  mcp.tool()(api_v1_archived_workflows_uid_resubmit.put_arch_wf_svc_resub_arch_wf)

  # Register api_v1_archived_workflows_uid_retry tools

  mcp.tool()(api_v1_archived_workflows_uid_retry.put_arch_wf_svc_retry_arch_wf)

  # Register api_v1_cluster_workflow_templates tools

  mcp.tool()(api_v1_cluster_workflow_templates.get_clust_wf_tpls)

  mcp.tool()(api_v1_cluster_workflow_templates.post_clust_wf_tpl)

  # Register api_v1_cluster_workflow_templates_lint tools

  mcp.tool()(api_v1_cluster_workflow_templates_lint.post_clust_wf_tpl)

  # Register api_v1_cluster_workflow_templates_name tools

  mcp.tool()(api_v1_cluster_workflow_templates_name.get_clust_wf_tpl)

  mcp.tool()(api_v1_cluster_workflow_templates_name.put_clust_wf_tpl)

  mcp.tool()(api_v1_cluster_workflow_templates_name.del_clust_wf_tpl)

  # Register api_v1_cron_workflows_namespace tools

  mcp.tool()(api_v1_cron_workflows_namespace.get_cron_wf_svc_ls_cron_wfs)

  mcp.tool()(api_v1_cron_workflows_namespace.post_cron_wf_svc_new_cron_wf)

  # Register api_v1_cron_workflows_namespace_lint tools

  mcp.tool()(api_v1_cron_workflows_namespace_lint.post_cron_wf_svc_lint_cron_wf)

  # Register api_v1_cron_workflows_namespace_name tools

  mcp.tool()(api_v1_cron_workflows_namespace_name.get_cron_wf_svc_get_cron_wf)

  mcp.tool()(api_v1_cron_workflows_namespace_name.put_cron_wf_svc_upd_cron_wf)

  mcp.tool()(api_v1_cron_workflows_namespace_name.del_cron_wf_svc_del_cron_wf)

  # Register api_v1_cron_workflows_namespace_name_resume tools

  mcp.tool()(api_v1_cron_workflows_namespace_name_resume.put_cron_wf_svc_res_cron_wf)

  # Register api_v1_cron_workflows_namespace_name_suspend tools

  mcp.tool()(api_v1_cron_workflows_namespace_name_suspend.put_cron_wf_svc_susp_cron_wf)

  # Register api_v1_event_sources_namespace tools

  mcp.tool()(api_v1_event_sources_namespace.get_evt_src_svc_ls_evt_srcs)

  mcp.tool()(api_v1_event_sources_namespace.post_evt_src_svc_new_evt_src)

  # Register api_v1_event_sources_namespace_name tools

  mcp.tool()(api_v1_event_sources_namespace_name.get_evt_src_svc_get_evt_src)

  mcp.tool()(api_v1_event_sources_namespace_name.put_evt_src_svc_upd_evt_src)

  mcp.tool()(api_v1_event_sources_namespace_name.del_evt_src_svc_del_evt_src)

  # Register api_v1_events_namespace_discriminator tools

  mcp.tool()(api_v1_events_namespace_discriminator.post_event_svc_receive_event)

  # Register api_v1_info tools

  mcp.tool()(api_v1_info.get_info_svc_get_info)

  # Register api_v1_sensors_namespace tools

  mcp.tool()(api_v1_sensors_namespace.get_sns_svc_ls_snss)

  mcp.tool()(api_v1_sensors_namespace.post_sns_svc_new_sns)

  # Register api_v1_sensors_namespace_name tools

  mcp.tool()(api_v1_sensors_namespace_name.get_sns_svc_get_sns)

  mcp.tool()(api_v1_sensors_namespace_name.put_sns_svc_upd_sns)

  mcp.tool()(api_v1_sensors_namespace_name.del_sns_svc_del_sns)

  # Register api_v1_stream_event_sources_namespace tools

  mcp.tool()(api_v1_stream_event_sources_namespace.get_evt_src_svc_watch_evt_srcs)

  # Register api_v1_stream_event_sources_namespace_logs tools

  mcp.tool()(api_v1_stream_event_sources_namespace_logs.get_evt_src_svc_evt_srcs_logs)

  # Register api_v1_stream_events_namespace tools

  mcp.tool()(api_v1_stream_events_namespace.get_wf_svc_watch_events)

  # Register api_v1_stream_sensors_namespace tools

  mcp.tool()(api_v1_stream_sensors_namespace.get_sns_svc_watch_snss)

  # Register api_v1_stream_sensors_namespace_logs tools

  mcp.tool()(api_v1_stream_sensors_namespace_logs.get_sns_svc_snss_logs)

  # Register api_v1_tracking_event tools

  mcp.tool()(api_v1_tracking_event.post_info_svc_collect_event)

  # Register api_v1_userinfo tools

  mcp.tool()(api_v1_userinfo.get_info_svc_get_user_info)

  # Register api_v1_version tools

  mcp.tool()(api_v1_version.get_info_svc_get_version)

  # Register api_v1_workflow_event_bindings_namespace tools

  mcp.tool()(api_v1_workflow_event_bindings_namespace.get_event_svc_ls_wf_event_bindings)

  # Register api_v1_workflow_events_namespace tools

  mcp.tool()(api_v1_workflow_events_namespace.get_wf_svc_watch_wfs)

  # Register api_v1_workflow_templates_namespace tools

  mcp.tool()(api_v1_workflow_templates_namespace.get_wf_tpl_svc_ls_wf_tpls)

  mcp.tool()(api_v1_workflow_templates_namespace.post_wf_tpl_svc_new_wf_tpl)

  # Register api_v1_workflow_templates_namespace_lint tools

  mcp.tool()(api_v1_workflow_templates_namespace_lint.post_wf_tpl_svc_lint_wf_tpl)

  # Register api_v1_workflow_templates_namespace_name tools

  mcp.tool()(api_v1_workflow_templates_namespace_name.get_wf_tpl_svc_get_wf_tpl)

  mcp.tool()(api_v1_workflow_templates_namespace_name.put_wf_tpl_svc_upd_wf_tpl)

  mcp.tool()(api_v1_workflow_templates_namespace_name.del_wf_tpl_svc_del_wf_tpl)

  # Register api_v1_workflows_namespace tools

  mcp.tool()(api_v1_workflows_namespace.get_wf_svc_ls_wfs)

  mcp.tool()(api_v1_workflows_namespace.post_wf_svc_new_wf)

  # Register api_v1_workflows_namespace_lint tools

  mcp.tool()(api_v1_workflows_namespace_lint.post_wf_svc_lint_wf)

  # Register api_v1_workflows_namespace_submit tools

  mcp.tool()(api_v1_workflows_namespace_submit.post_wf_svc_submit_wf)

  # Register api_v1_workflows_namespace_name tools

  mcp.tool()(api_v1_workflows_namespace_name.get_wf_svc_get_wf)

  mcp.tool()(api_v1_workflows_namespace_name.del_wf_svc_del_wf)

  # Register api_v1_workflows_namespace_name_log tools

  mcp.tool()(api_v1_workflows_namespace_name_log.get_wf_svc_wf_logs)

  # Register api_v1_workflows_namespace_name_resubmit tools

  mcp.tool()(api_v1_workflows_namespace_name_resubmit.put_wf_svc_resub_wf)

  # Register api_v1_workflows_namespace_name_resume tools

  mcp.tool()(api_v1_workflows_namespace_name_resume.put_wf_svc_res_wf)

  # Register api_v1_workflows_namespace_name_retry tools

  mcp.tool()(api_v1_workflows_namespace_name_retry.put_wf_svc_retry_wf)

  # Register api_v1_workflows_namespace_name_set tools

  mcp.tool()(api_v1_workflows_namespace_name_set.put_wf_svc_set_wf)

  # Register api_v1_workflows_namespace_name_stop tools

  mcp.tool()(api_v1_workflows_namespace_name_stop.put_wf_svc_stop_wf)

  # Register api_v1_workflows_namespace_name_suspend tools

  mcp.tool()(api_v1_workflows_namespace_name_suspend.put_wf_svc_susp_wf)

  # Register api_v1_workflows_namespace_name_terminate tools

  mcp.tool()(api_v1_workflows_namespace_name_terminate.put_wf_svc_term_wf)

  # Register api_v1_workflows_namespace_name_podname_log tools

  mcp.tool()(api_v1_workflows_namespace_name_podname_log.get_wf_svc_pod_logs)

  # Register artifact_files_namespace_iddiscriminator_id_nodeid_artifactdiscriminator_artifactname tools

  mcp.tool()(artifact_files_namespace_iddiscriminator_id_nodeid_artifactdiscriminator_artifactname.get_art_svc_get_art_file)

  # Register artifacts_by_uid_uid_nodeid_artifactname tools

  mcp.tool()(artifacts_by_uid_uid_nodeid_artifactname.get_art_svc_get_output_art_uid)

  # Register artifacts_namespace_name_nodeid_artifactname tools

  mcp.tool()(artifacts_namespace_name_nodeid_artifactname.get_art_svc_get_output_art)

  # Register input_artifacts_by_uid_uid_nodeid_artifactname tools

  mcp.tool()(input_artifacts_by_uid_uid_nodeid_artifactname.get_art_svc_get_input_art_uid)

  # Register input_artifacts_namespace_name_nodeid_artifactname tools

  mcp.tool()(input_artifacts_namespace_name_nodeid_artifactname.get_art_svc_get_input_art)

  # Run the MCP server
  mcp.run(transport=MCP_MODE.lower())


if __name__ == "__main__":
  main()
