
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /pet operations"""

import logging
from typing import Dict, Any
from mcp_petstore.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def updatepet() -> Dict[str, Any]:
    '''
    Update an existing pet.

    Args:
        None

    Returns:
        Dict[str, Any]: The response from the API containing the updated pet information or an error message.

    Raises:
        Exception: If the API request fails due to network issues or invalid response.

    OpenAPI Specification:
        put:
          summary: Update an existing pet
          description: Update the details of an existing pet in the store.
          operationId: updatePet
          requestBody:
            description: Pet object that needs to be updated in the store
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Pet'
          responses:
            '200':
              description: Successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Pet'
            '400':
              description: Invalid ID supplied
            '404':
              description: Pet not found
            '405':
              description: Validation exception
          tags:
            - pet
    '''
    logger.debug("Making PUT request to /pet")
    params = {}
    data = None

    success, response = await make_api_request(
        "/pet",
        method="PUT",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def addpet() -> Dict[str, Any]:
    '''
    Add a new pet to the store.

    Args:
        None

    Returns:
        Dict[str, Any]: The response from the API containing the details of the added pet or an error message.

    Raises:
        Exception: If the API request fails due to network issues or invalid response.

    OpenAPI Specification:
      post:
        summary: Add a new pet to the store
        operationId: addPet
        tags:
          - pet
        requestBody:
          description: Pet object that needs to be added to the store
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Pet'
          '400':
            description: Invalid input
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
    '''
    logger.debug("Making POST request to /pet")
    params = {}
    data = None

    success, response = await make_api_request(
        "/pet",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response
