
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /pet operations"""

import logging
from typing import Dict, Any
from mcp_petstore.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def updatePet() -> Dict[str, Any]:
    """
    Update an existing pet.
    
    Returns:
        API response data
    """
    logger.debug("Making PUT request to /pet")
    params = {}
    data = None
    
    success, response = await make_api_request(
        "/pet",
        method="PUT",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def addPet() -> Dict[str, Any]:
    """
    Add a new pet to the store.
    
    Returns:
        API response data
    """
    logger.debug("Making POST request to /pet")
    params = {}
    data = None
    
    success, response = await make_api_request(
        "/pet",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response

