# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /pet/{petId} operations"""

import logging
from typing import Dict, Any
from mcp_petstore.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def get_pet_by_id(path_petId: int) -> Dict[str, Any]:
    """
    Find pet by ID.

    OpenAPI Description:
        Returns a single pet.

    Args:
    path_petId (int): OpenAPI parameter corresponding to 'path_petId'.


    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /pet/{petId}")

    params = {}
    data = {}

    success, response = await make_api_request(f"/pet/{path_petId}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def update_pet_with_form(path_petId: int, param_name: str = None, param_status: str = None) -> Dict[str, Any]:
    """
    Updates a pet in the store with form data.

    OpenAPI Description:
        Updates a pet resource based on the form data.

    Args:
    path_petId (int): OpenAPI parameter corresponding to 'path_petId'.
    param_name (str = None): OpenAPI parameter corresponding to 'param_name'.
    param_status (str = None): OpenAPI parameter corresponding to 'param_status'.


    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /pet/{petId}")

    params = {}
    data = {}

    params["name"] = param_name
    params["status"] = param_status

    success, response = await make_api_request(f"/pet/{path_petId}", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def delete_pet(path_petId: int) -> Dict[str, Any]:
    """
    Deletes a pet.

    OpenAPI Description:
        Delete a pet.

    Args:
    path_petId (int): OpenAPI parameter corresponding to 'path_petId'.


    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making DELETE request to /pet/{petId}")

    params = {}
    data = {}

    success, response = await make_api_request(f"/pet/{path_petId}", method="DELETE", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
