# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /pet/findByStatus operations"""

import logging
from typing import Dict, Any
from mcp_petstore.api.client import make_api_request


def assemble_nested_body(flat_body: Dict[str, Any]) -> Dict[str, Any]:
    '''
    Convert a flat dictionary with underscore-separated keys into a nested dictionary.

    Args:
        flat_body (Dict[str, Any]): A dictionary where keys are underscore-separated strings representing nested paths.

    Returns:
        Dict[str, Any]: A nested dictionary constructed from the flat dictionary.

    Raises:
        ValueError: If the input dictionary contains invalid keys that cannot be split into parts.
    '''
    nested = {}
    for key, value in flat_body.items():
        parts = key.split("_")
        d = nested
        for part in parts[:-1]:
            d = d.setdefault(part, {})
        d[parts[-1]] = value
    return nested


# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def find_pets_by_status(param_status: str = None) -> Dict[str, Any]:
    '''
    Finds pets by their status.

    Args:
        param_status (str, optional): Status values that need to be considered for filtering. Multiple status values can be provided as comma-separated strings. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the list of pets matching the given status.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /pet/findByStatus")

    params = {}
    data = {}

    params["status"] = str(param_status).lower() if isinstance(param_status, bool) else param_status

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request("/pet/findByStatus", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response