# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /store/order/{orderId} operations"""

import logging
from typing import Dict, Any
from mcp_petstore.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def get_order_by_id(path_orderId: int) -> Dict[str, Any]:
    '''
    Find a purchase order by its ID.

    Args:
        path_orderId (int): The ID of the order to fetch. Valid IDs are integers with value <= 5 or > 10. Other values will generate exceptions.

    Returns:
        Dict[str, Any]: The JSON response containing the order details if found, or an error message if not.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /store/order/{orderId}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/store/order/{path_orderId}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def delete_order(path_orderId: int) -> Dict[str, Any]:
    '''
    Delete a purchase order by its identifier.

    For a valid response, use integer order IDs with values less than 1000. IDs greater than or equal to 1000, or non-integer values, will result in API errors.

    Args:
        path_orderId (int): The ID of the order that needs to be deleted.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the result of the delete operation or error details.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making DELETE request to /store/order/{orderId}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/store/order/{path_orderId}", method="DELETE", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response