# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /store/inventory operations"""

import logging
from typing import Any
from mcp_petstore.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def get_inventory() -> Any:
  '''
  Retrieves pet inventories grouped by status.

  Args:
      None

  Returns:
      Any: A dictionary mapping status codes to quantities, representing the inventory of pets by status.

  Raises:
      Exception: If the API request fails or an error occurs during the retrieval process.
  '''
  logger.debug("Making GET request to /store/inventory")

  params = {}
  data = {}

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/store/inventory", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response