---
name: Conventional Commits

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request:

# Declare default permissions as read-only
permissions: read-all

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: 🧹 Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0

