---
name: Super Linter

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request:

# Declare default permissions as read-only
permissions: read-all

jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e  # v2.14.2
        with:
          egress-policy: audit
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.7
        with:
          fetch-depth: 0
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@12562e48d7059cf666c43a4ecb0d3b5a2b31bd9e  # v8.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITLEAKS: true
