# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/cron-workflows/{namespace}/lint operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def cron_workflow_service_lint_cron_workflow(
    path_namespace: str,
    body_cronWorkflow_apiVersion: str = None,
    body_cronWorkflow_kind: str = None,
    body_cronWorkflow_metadata: Dict[str, Any] = None,
    body_cronWorkflow_spec: Dict[str, Any] = None,
    body_cronWorkflow_status_active: List[Dict[str, Any]] = None,
    body_cronWorkflow_status_conditions: List[Dict[str, Any]] = None,
    body_cronWorkflow_status_failed: int = None,
    body_cronWorkflow_status_lastScheduledTime: str = None,
    body_cronWorkflow_status_phase: str = None,
    body_cronWorkflow_status_succeeded: int = None,
    body_namespace: str = None,
) -> Any:
    """
    Perform an operation on lint

    OpenAPI Description:
        Perform an operation on lint Use when: when initializing new resources based on user requirements. Required: namespace, body

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        body_cronWorkflow_apiVersion (str): APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources

        body_cronWorkflow_kind (str): Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

        body_cronWorkflow_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

        body_cronWorkflow_spec (Dict[str, Any]): CronWorkflowSpec is the specification of a CronWorkflow

        body_cronWorkflow_status_active (List[Dict[str, Any]]): Active is a list of active workflows stemming from this CronWorkflow

        body_cronWorkflow_status_conditions (List[Dict[str, Any]]): Conditions is a list of conditions the CronWorkflow may have

        body_cronWorkflow_status_failed (int): v3.6 and after: Failed counts how many times child workflows failed

        body_cronWorkflow_status_lastScheduledTime (str): Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.

        body_cronWorkflow_status_phase (str): v3.6 and after: Phase is an enum of Active or Stopped. It changes to Stopped when stopStrategy.expression is true

        body_cronWorkflow_status_succeeded (int): v3.6 and after: Succeeded counts how many times child workflows succeeded

        body_namespace (str): OpenAPI parameter corresponding to 'body_namespace'


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /api/v1/cron-workflows/{namespace}/lint")

    params = {}
    data = {}

    flat_body = {}
    if body_cronWorkflow_apiVersion is not None:
        flat_body["cronWorkflow_apiVersion"] = body_cronWorkflow_apiVersion
    if body_cronWorkflow_kind is not None:
        flat_body["cronWorkflow_kind"] = body_cronWorkflow_kind
    if body_cronWorkflow_metadata is not None:
        flat_body["cronWorkflow_metadata"] = body_cronWorkflow_metadata
    if body_cronWorkflow_spec is not None:
        flat_body["cronWorkflow_spec"] = body_cronWorkflow_spec
    if body_cronWorkflow_status_active is not None:
        flat_body["cronWorkflow_status_active"] = body_cronWorkflow_status_active
    if body_cronWorkflow_status_conditions is not None:
        flat_body["cronWorkflow_status_conditions"] = body_cronWorkflow_status_conditions
    if body_cronWorkflow_status_failed is not None:
        flat_body["cronWorkflow_status_failed"] = body_cronWorkflow_status_failed
    if body_cronWorkflow_status_lastScheduledTime is not None:
        flat_body["cronWorkflow_status_lastScheduledTime"] = body_cronWorkflow_status_lastScheduledTime
    if body_cronWorkflow_status_phase is not None:
        flat_body["cronWorkflow_status_phase"] = body_cronWorkflow_status_phase
    if body_cronWorkflow_status_succeeded is not None:
        flat_body["cronWorkflow_status_succeeded"] = body_cronWorkflow_status_succeeded
    if body_namespace is not None:
        flat_body["namespace"] = body_namespace
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/cron-workflows/{path_namespace}/lint", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
