# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/workflow-templates/{namespace}/lint operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def workflow_template_service_lint_workflow_template(
    path_namespace: str,
    body_create_options_dry_run: List[str] = None,
    body_create_options_fieldManager: str = None,
    body_create_options_fieldValidation: str = None,
    body_namespace: str = None,
    body_template_apiVersion: str = None,
    body_template_kind: str = None,
    body_template_metadata: Dict[str, Any] = None,
    body_template_spec: Dict[str, Any] = None,
) -> Any:
    """
    Perform an operation on lint

    OpenAPI Description:
        Perform an operation on lint Use when: when initializing new resources based on user requirements. Required: namespace, body

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        body_create_options_dry_run (List[str]): OpenAPI parameter corresponding to 'body_create_options_dry_run'

        body_create_options_fieldManager (str): OpenAPI parameter corresponding to 'body_create_options_fieldManager'

        body_create_options_fieldValidation (str): OpenAPI parameter corresponding to 'body_create_options_fieldValidation'

        body_namespace (str): OpenAPI parameter corresponding to 'body_namespace'

        body_template_apiVersion (str): APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources

        body_template_kind (str): Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

        body_template_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

        body_template_spec (Dict[str, Any]): WorkflowSpec is the specification of a Workflow.


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /api/v1/workflow-templates/{namespace}/lint")

    params = {}
    data = {}

    flat_body = {}
    if body_create_options_dry_run is not None:
        flat_body["create_options_dry_run"] = body_create_options_dry_run
    if body_create_options_fieldManager is not None:
        flat_body["create_options_fieldManager"] = body_create_options_fieldManager
    if body_create_options_fieldValidation is not None:
        flat_body["create_options_fieldValidation"] = body_create_options_fieldValidation
    if body_namespace is not None:
        flat_body["namespace"] = body_namespace
    if body_template_apiVersion is not None:
        flat_body["template_apiVersion"] = body_template_apiVersion
    if body_template_kind is not None:
        flat_body["template_kind"] = body_template_kind
    if body_template_metadata is not None:
        flat_body["template_metadata"] = body_template_metadata
    if body_template_spec is not None:
        flat_body["template_spec"] = body_template_spec
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/workflow-templates/{path_namespace}/lint", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
