# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/workflows/{namespace}/submit operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def workflow_service_submit_workflow(path_namespace: str) -> Any:
  """
  Perform an operation on submit

  OpenAPI Description:
      Submits a new workflow for execution. Use when: initiating a workflow process in a specified namespace.

  Args:

      path_namespace (str): Specifies the Kubernetes namespace for the workflow submission.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making POST request to /api/v1/workflows/{namespace}/submit")

  params = {}
  data = {}

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(f"/api/v1/workflows/{path_namespace}/submit", method="POST", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
