# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/archived-workflows-label-values operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def arch_wf_svc_list_arch_wf_label_values(
    param_list_options_label_selector: str = None,
    param_list_options_field_selector: str = None,
    param_list_options_watch: bool = False,
    param_list_options_allow_watch_bookmarks: bool = False,
    param_list_options_resource_version: str = None,
    param_list_options_resource_versionMatch: str = None,
    param_list_options_timeout_seconds: str = None,
    param_list_options_limit: str = None,
    param_list_options_continue: str = None,
    param_list_options_send_initial_events: bool = False,
    param_namespace: str = None,
) -> Any:
    """
    List or query archived-workflows-label-values

    OpenAPI Description:
        List or query archived-workflows-label-values Use when: when you need to discover available resources or check what exists

    Args:

        param_list_options_label_selector (str): A selector to restrict the list of returned objects by their labels. Defaults to...

        param_list_options_field_selector (str): A selector to restrict the list of returned objects by their fields. Defaults to...

        param_list_options_watch (bool): Watch for changes to the described resources and return them as a stream of add,...

        param_list_options_allow_watch_bookmarks (bool): allow_watch_bookmarks requests watch events with type "BOOKMARK". Servers that do ...

        param_list_options_resource_version (str): resource_version sets a constraint on what resource versions a request may be ser...

        param_list_options_resource_versionMatch (str): resource_versionMatch determines how resource_version is applied to list calls. It...

        param_list_options_timeout_seconds (str): Timeout for the list/watch call. This limits the duration of the call, regardles...

        param_list_options_limit (str): limit is a maximum number of responses to return for a list call. If more items ...

        param_list_options_continue (str): The continue option should be set when retrieving more results from the server. ...

        param_list_options_send_initial_events (bool): `send_initial_events=true` may be set together with `watch=true`. In that case, th...

        param_namespace (str): Kubernetes namespace to scope the operation


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/archived-workflows-label-values")

    params = {}
    data = {}

    if param_list_options_label_selector is not None:
        params["list_options_label_selector"] = (
            str(param_list_options_label_selector).lower()
            if isinstance(param_list_options_label_selector, bool)
            else param_list_options_label_selector
        )

    if param_list_options_field_selector is not None:
        params["list_options_field_selector"] = (
            str(param_list_options_field_selector).lower()
            if isinstance(param_list_options_field_selector, bool)
            else param_list_options_field_selector
        )

    if param_list_options_watch is not None:
        params["list_options_watch"] = (
            str(param_list_options_watch).lower() if isinstance(param_list_options_watch, bool) else param_list_options_watch
        )

    if param_list_options_allow_watch_bookmarks is not None:
        params["list_options_allow_watch_bookmarks"] = (
            str(param_list_options_allow_watch_bookmarks).lower()
            if isinstance(param_list_options_allow_watch_bookmarks, bool)
            else param_list_options_allow_watch_bookmarks
        )

    if param_list_options_resource_version is not None:
        params["list_options_resource_version"] = (
            str(param_list_options_resource_version).lower()
            if isinstance(param_list_options_resource_version, bool)
            else param_list_options_resource_version
        )

    if param_list_options_resource_versionMatch is not None:
        params["list_options_resource_versionMatch"] = (
            str(param_list_options_resource_versionMatch).lower()
            if isinstance(param_list_options_resource_versionMatch, bool)
            else param_list_options_resource_versionMatch
        )

    if param_list_options_timeout_seconds is not None:
        params["list_options_timeout_seconds"] = (
            str(param_list_options_timeout_seconds).lower()
            if isinstance(param_list_options_timeout_seconds, bool)
            else param_list_options_timeout_seconds
        )

    if param_list_options_limit is not None:
        params["list_options_limit"] = (
            str(param_list_options_limit).lower() if isinstance(param_list_options_limit, bool) else param_list_options_limit
        )

    if param_list_options_continue is not None:
        params["list_options_continue"] = (
            str(param_list_options_continue).lower() if isinstance(param_list_options_continue, bool) else param_list_options_continue
        )

    if param_list_options_send_initial_events is not None:
        params["list_options_send_initial_events"] = (
            str(param_list_options_send_initial_events).lower()
            if isinstance(param_list_options_send_initial_events, bool)
            else param_list_options_send_initial_events
        )

    if param_namespace is not None:
        params["namespace"] = str(param_namespace).lower() if isinstance(param_namespace, bool) else param_namespace

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request("/api/v1/archived-workflows-label-values", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
