# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/event-sources/{namespace} operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def event_source_service_list_event_sources(
    path_namespace: str,
    param_list_options_label_selector: str = None,
    param_list_options_field_selector: str = None,
    param_list_options_watch: bool = False,
    param_list_options_allow_watch_bookmarks: bool = False,
    param_list_options_resource_version: str = None,
    param_list_options_resource_versionMatch: str = None,
    param_list_options_timeout_seconds: str = None,
    param_list_options_limit: str = None,
    param_list_options_continue: str = None,
    param_list_options_send_initial_events: bool = False,
) -> Any:
    """
    Retrieve details of a specific event-sources

    OpenAPI Description:
        Retrieve details of a specific event-sources Use when: when you need to discover available resources or check what exists. Required: namespace

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        param_list_options_label_selector (str): A selector to restrict the list of returned objects by their labels. Defaults to...

        param_list_options_field_selector (str): A selector to restrict the list of returned objects by their fields. Defaults to...

        param_list_options_watch (bool): Watch for changes to the described resources and return them as a stream of add,...

        param_list_options_allow_watch_bookmarks (bool): allow_watch_bookmarks requests watch events with type "BOOKMARK". Servers that do ...

        param_list_options_resource_version (str): resource_version sets a constraint on what resource versions a request may be ser...

        param_list_options_resource_versionMatch (str): resource_versionMatch determines how resource_version is applied to list calls. It...

        param_list_options_timeout_seconds (str): Timeout for the list/watch call. This limits the duration of the call, regardles...

        param_list_options_limit (str): limit is a maximum number of responses to return for a list call. If more items ...

        param_list_options_continue (str): The continue option should be set when retrieving more results from the server. ...

        param_list_options_send_initial_events (bool): `send_initial_events=true` may be set together with `watch=true`. In that case, th...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/event-sources/{namespace}")

    params = {}
    data = {}

    if param_list_options_label_selector is not None:
        params["list_options_label_selector"] = (
            str(param_list_options_label_selector).lower()
            if isinstance(param_list_options_label_selector, bool)
            else param_list_options_label_selector
        )

    if param_list_options_field_selector is not None:
        params["list_options_field_selector"] = (
            str(param_list_options_field_selector).lower()
            if isinstance(param_list_options_field_selector, bool)
            else param_list_options_field_selector
        )

    if param_list_options_watch is not None:
        params["list_options_watch"] = (
            str(param_list_options_watch).lower() if isinstance(param_list_options_watch, bool) else param_list_options_watch
        )

    if param_list_options_allow_watch_bookmarks is not None:
        params["list_options_allow_watch_bookmarks"] = (
            str(param_list_options_allow_watch_bookmarks).lower()
            if isinstance(param_list_options_allow_watch_bookmarks, bool)
            else param_list_options_allow_watch_bookmarks
        )

    if param_list_options_resource_version is not None:
        params["list_options_resource_version"] = (
            str(param_list_options_resource_version).lower()
            if isinstance(param_list_options_resource_version, bool)
            else param_list_options_resource_version
        )

    if param_list_options_resource_versionMatch is not None:
        params["list_options_resource_versionMatch"] = (
            str(param_list_options_resource_versionMatch).lower()
            if isinstance(param_list_options_resource_versionMatch, bool)
            else param_list_options_resource_versionMatch
        )

    if param_list_options_timeout_seconds is not None:
        params["list_options_timeout_seconds"] = (
            str(param_list_options_timeout_seconds).lower()
            if isinstance(param_list_options_timeout_seconds, bool)
            else param_list_options_timeout_seconds
        )

    if param_list_options_limit is not None:
        params["list_options_limit"] = (
            str(param_list_options_limit).lower() if isinstance(param_list_options_limit, bool) else param_list_options_limit
        )

    if param_list_options_continue is not None:
        params["list_options_continue"] = (
            str(param_list_options_continue).lower() if isinstance(param_list_options_continue, bool) else param_list_options_continue
        )

    if param_list_options_send_initial_events is not None:
        params["list_options_send_initial_events"] = (
            str(param_list_options_send_initial_events).lower()
            if isinstance(param_list_options_send_initial_events, bool)
            else param_list_options_send_initial_events
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/event-sources/{path_namespace}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def event_source_service_create_event_source(
    path_namespace: str,
    body_eventSource_metadata: Dict[str, Any] = None,
    body_eventSource_spec: Dict[str, Any] = None,
    body_eventSource_status_status_conditions: List[Dict[str, Any]] = None,
    body_namespace: str = None,
) -> Any:
    """
    Create a new event-sources

    OpenAPI Description:
        Create a new event-sources Use when: when initializing new resources based on user requirements. Required: namespace, body

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        body_eventSource_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

        body_eventSource_spec (Dict[str, Any]): Request body as dictionary. Contains 35 nested properties. See OpenAPI schema for detailed structure.

        body_eventSource_status_status_conditions (List[Dict[str, Any]]): OpenAPI parameter corresponding to 'body_eventSource_status_status_conditions'

        body_namespace (str): OpenAPI parameter corresponding to 'body_namespace'


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /api/v1/event-sources/{namespace}")

    params = {}
    data = {}

    flat_body = {}
    if body_eventSource_metadata is not None:
        flat_body["eventSource_metadata"] = body_eventSource_metadata
    if body_eventSource_spec is not None:
        flat_body["eventSource_spec"] = body_eventSource_spec
    if body_eventSource_status_status_conditions is not None:
        flat_body["eventSource_status_status_conditions"] = body_eventSource_status_status_conditions
    if body_namespace is not None:
        flat_body["namespace"] = body_namespace
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/event-sources/{path_namespace}", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
