# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/workflows/{namespace}/{name}/resubmit operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def workflow_service_resubmit_workflow(path_namespace: str, path_name: str) -> Any:
  """
  Update or replace a resubmit

  OpenAPI Description:
      Resubmits a workflow by name. Use when: retrying a failed workflow or reprocessing with the same configuration.

  Args:

      path_namespace (str): "Kubernetes namespace for the workflow to resubmit"

      path_name (str): Workflow name to resubmit in the specified namespace.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making PUT request to /api/v1/workflows/{namespace}/{name}/resubmit")

  params = {}
  data = {}

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(
    f"/api/v1/workflows/{path_namespace}/{path_name}/resubmit", method="PUT", params=params, data=data
  )

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
