# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/cluster-workflow-templates/{name} operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def cwt_svc_get_cwt(path_name: str, param_getOptions_resource_version: str = None) -> Any:
    """
    Retrieve details of a specific cluster-workflow-templates

    OpenAPI Description:
        Retrieve details of a specific cluster-workflow-templates Use when: when you have a specific resource identifier and need its current details. Required: name

    Args:

        path_name (str): Name of the resource to operate on

        param_getOptions_resource_version (str): resource_version sets a constraint on what resource versions a request may be ser...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/cluster-workflow-templates/{name}")

    params = {}
    data = {}

    if param_getOptions_resource_version is not None:
        params["getOptions_resource_version"] = (
            str(param_getOptions_resource_version).lower()
            if isinstance(param_getOptions_resource_version, bool)
            else param_getOptions_resource_version
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/cluster-workflow-templates/{path_name}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def cwt_svc_update_cwt(
    path_name: str,
    body_name: str = None,
    body_template_apiVersion: str = None,
    body_template_kind: str = None,
    body_template_metadata: Dict[str, Any] = None,
    body_template_spec: Dict[str, Any] = None,
) -> Any:
    """
    Update or replace a cluster-workflow-templates

    OpenAPI Description:
        Update or replace a cluster-workflow-templates Use when: when modifying existing resource configurations or properties. Required: name, body

    Args:

        path_name (str): DEPRECATED: This field is ignored.

        body_name (str): DEPRECATED: This field is ignored.

        body_template_apiVersion (str): APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources

        body_template_kind (str): Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

        body_template_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

        body_template_spec (Dict[str, Any]): WorkflowSpec is the specification of a Workflow.


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making PUT request to /api/v1/cluster-workflow-templates/{name}")

    params = {}
    data = {}

    flat_body = {}
    if body_name is not None:
        flat_body["name"] = body_name
    if body_template_apiVersion is not None:
        flat_body["template_apiVersion"] = body_template_apiVersion
    if body_template_kind is not None:
        flat_body["template_kind"] = body_template_kind
    if body_template_metadata is not None:
        flat_body["template_metadata"] = body_template_metadata
    if body_template_spec is not None:
        flat_body["template_spec"] = body_template_spec
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/cluster-workflow-templates/{path_name}", method="PUT", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def cwt_svc_delete_cwt(
    path_name: str,
    param_delete_options_grace_period_seconds: str = None,
    param_delete_options_preconditions_uid: str = None,
    param_delete_options_preconditions_resource_version: str = None,
    param_delete_options_orphan_dependents: bool = False,
    param_delete_options_propagation_policy: str = None,
    param_delete_options_dry_run: List[str] = None,
    param_delete_options_ignore_store_read_error: bool = False,
) -> Any:
    """
    Delete a cluster-workflow-templates

    OpenAPI Description:
        Delete a cluster-workflow-templates Use when: when cleaning up resources that are no longer needed. Required: name

    Args:

        path_name (str): Name of the resource to operate on

        param_delete_options_grace_period_seconds (str): The duration in seconds before the object should be deleted. Value must be non-n...

        param_delete_options_preconditions_uid (str): Specifies the target UID. +optional.

        param_delete_options_preconditions_resource_version (str): Specifies the target ResourceVersion +optional.

        param_delete_options_orphan_dependents (bool): Deprecated: please use the PropagationPolicy, this field will be deprecated in 1...

        param_delete_options_propagation_policy (str): Whether and how garbage collection will be performed. Either this field or Orpha...

        param_delete_options_dry_run (List[str]): When present, indicates that modifications should not be persisted. An invalid o...

        param_delete_options_ignore_store_read_error (bool): if set to true, it will trigger an unsafe deletion of the resource in case the n...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making DELETE request to /api/v1/cluster-workflow-templates/{name}")

    params = {}
    data = {}

    if param_delete_options_grace_period_seconds is not None:
        params["delete_options_grace_period_seconds"] = (
            str(param_delete_options_grace_period_seconds).lower()
            if isinstance(param_delete_options_grace_period_seconds, bool)
            else param_delete_options_grace_period_seconds
        )

    if param_delete_options_preconditions_uid is not None:
        params["delete_options_preconditions_uid"] = (
            str(param_delete_options_preconditions_uid).lower()
            if isinstance(param_delete_options_preconditions_uid, bool)
            else param_delete_options_preconditions_uid
        )

    if param_delete_options_preconditions_resource_version is not None:
        params["delete_options_preconditions_resource_version"] = (
            str(param_delete_options_preconditions_resource_version).lower()
            if isinstance(param_delete_options_preconditions_resource_version, bool)
            else param_delete_options_preconditions_resource_version
        )

    if param_delete_options_orphan_dependents is not None:
        params["delete_options_orphan_dependents"] = (
            str(param_delete_options_orphan_dependents).lower()
            if isinstance(param_delete_options_orphan_dependents, bool)
            else param_delete_options_orphan_dependents
        )

    if param_delete_options_propagation_policy is not None:
        params["delete_options_propagation_policy"] = (
            str(param_delete_options_propagation_policy).lower()
            if isinstance(param_delete_options_propagation_policy, bool)
            else param_delete_options_propagation_policy
        )

    if param_delete_options_dry_run is not None:
        params["delete_options_dry_run"] = (
            str(param_delete_options_dry_run).lower() if isinstance(param_delete_options_dry_run, bool) else param_delete_options_dry_run
        )

    if param_delete_options_ignore_store_read_error is not None:
        params["delete_options_ignore_store_read_error"] = (
            str(param_delete_options_ignore_store_read_error).lower()
            if isinstance(param_delete_options_ignore_store_read_error, bool)
            else param_delete_options_ignore_store_read_error
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/cluster-workflow-templates/{path_name}", method="DELETE", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
