# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/cron-workflows/{namespace} operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def cron_workflow_service_list_cron_workflows(
    path_namespace: str,
    param_listOptions_labelSelector: str = None,
    param_listOptions_fieldSelector: str = None,
    param_listOptions_watch: bool = False,
    param_listOptions_allowWatchBookmarks: bool = False,
    param_listOptions_resourceVersion: str = None,
    param_listOptions_resourceVersionMatch: str = None,
    param_listOptions_timeoutSeconds: str = None,
    param_listOptions_limit: str = None,
    param_listOptions_continue: str = None,
    param_listOptions_sendInitialEvents: bool = False,
) -> Any:
    """
    Retrieve details of a specific cron-workflows

    OpenAPI Description:
        Retrieve details of a specific cron-workflows Use when: when you need to discover available resources or check what exists. Required: namespace

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        param_listOptions_labelSelector (str): A selector to restrict the list of returned objects by their labels. Defaults to...

        param_listOptions_fieldSelector (str): A selector to restrict the list of returned objects by their fields. Defaults to...

        param_listOptions_watch (bool): Watch for changes to the described resources and return them as a stream of add,...

        param_listOptions_allowWatchBookmarks (bool): allowWatchBookmarks requests watch events with type "BOOKMARK". Servers that do ...

        param_listOptions_resourceVersion (str): resourceVersion sets a constraint on what resource versions a request may be ser...

        param_listOptions_resourceVersionMatch (str): resourceVersionMatch determines how resourceVersion is applied to list calls. It...

        param_listOptions_timeoutSeconds (str): Timeout for the list/watch call. This limits the duration of the call, regardles...

        param_listOptions_limit (str): limit is a maximum number of responses to return for a list call. If more items ...

        param_listOptions_continue (str): The continue option should be set when retrieving more results from the server. ...

        param_listOptions_sendInitialEvents (bool): `sendInitialEvents=true` may be set together with `watch=true`. In that case, th...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/cron-workflows/{namespace}")

    params = {}
    data = {}

    if param_listOptions_labelSelector is not None:
        params["listOptions_labelSelector"] = (
            str(param_listOptions_labelSelector).lower()
            if isinstance(param_listOptions_labelSelector, bool)
            else param_listOptions_labelSelector
        )

    if param_listOptions_fieldSelector is not None:
        params["listOptions_fieldSelector"] = (
            str(param_listOptions_fieldSelector).lower()
            if isinstance(param_listOptions_fieldSelector, bool)
            else param_listOptions_fieldSelector
        )

    if param_listOptions_watch is not None:
        params["listOptions_watch"] = (
            str(param_listOptions_watch).lower() if isinstance(param_listOptions_watch, bool) else param_listOptions_watch
        )

    if param_listOptions_allowWatchBookmarks is not None:
        params["listOptions_allowWatchBookmarks"] = (
            str(param_listOptions_allowWatchBookmarks).lower()
            if isinstance(param_listOptions_allowWatchBookmarks, bool)
            else param_listOptions_allowWatchBookmarks
        )

    if param_listOptions_resourceVersion is not None:
        params["listOptions_resourceVersion"] = (
            str(param_listOptions_resourceVersion).lower()
            if isinstance(param_listOptions_resourceVersion, bool)
            else param_listOptions_resourceVersion
        )

    if param_listOptions_resourceVersionMatch is not None:
        params["listOptions_resourceVersionMatch"] = (
            str(param_listOptions_resourceVersionMatch).lower()
            if isinstance(param_listOptions_resourceVersionMatch, bool)
            else param_listOptions_resourceVersionMatch
        )

    if param_listOptions_timeoutSeconds is not None:
        params["listOptions_timeoutSeconds"] = (
            str(param_listOptions_timeoutSeconds).lower()
            if isinstance(param_listOptions_timeoutSeconds, bool)
            else param_listOptions_timeoutSeconds
        )

    if param_listOptions_limit is not None:
        params["listOptions_limit"] = (
            str(param_listOptions_limit).lower() if isinstance(param_listOptions_limit, bool) else param_listOptions_limit
        )

    if param_listOptions_continue is not None:
        params["listOptions_continue"] = (
            str(param_listOptions_continue).lower() if isinstance(param_listOptions_continue, bool) else param_listOptions_continue
        )

    if param_listOptions_sendInitialEvents is not None:
        params["listOptions_sendInitialEvents"] = (
            str(param_listOptions_sendInitialEvents).lower()
            if isinstance(param_listOptions_sendInitialEvents, bool)
            else param_listOptions_sendInitialEvents
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/cron-workflows/{path_namespace}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def cron_workflow_service_create_cron_workflow(
    path_namespace: str,
    body_createOptions__dryRun: List[str] = None,
    body_createOptions__fieldManager: str = None,
    body_createOptions__fieldValidation: str = None,
    body_cronWorkflow__apiVersion: str = None,
    body_cronWorkflow__kind: str = None,
    body_cronWorkflow__metadata: Dict[str, Any] = None,
    body_cronWorkflow__spec: Dict[str, Any] = None,
    body_cronWorkflow__status__active: List[Dict[str, Any]] = None,
    body_cronWorkflow__status__conditions: List[Dict[str, Any]] = None,
    body_cronWorkflow__status__failed: int = None,
    body_cronWorkflow__status__lastScheduledTime: str = None,
    body_cronWorkflow__status__phase: str = None,
    body_cronWorkflow__status__succeeded: int = None,
    body_namespace: str = None,
) -> Any:
    """
    Create a new cron-workflows

    OpenAPI Description:
        Create a new cron-workflows Use when: when initializing new resources based on user requirements. Required: namespace, body

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        body_createOptions__dryRun (List[str]): OpenAPI parameter corresponding to 'body_createOptions__dryRun'

        body_createOptions__fieldManager (str): OpenAPI parameter corresponding to 'body_createOptions__fieldManager'

        body_createOptions__fieldValidation (str): OpenAPI parameter corresponding to 'body_createOptions__fieldValidation'

        body_cronWorkflow__apiVersion (str): APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources

        body_cronWorkflow__kind (str): Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

        body_cronWorkflow__metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

        body_cronWorkflow__spec (Dict[str, Any]): CronWorkflowSpec is the specification of a CronWorkflow

        body_cronWorkflow__status__active (List[Dict[str, Any]]): Active is a list of active workflows stemming from this CronWorkflow

        body_cronWorkflow__status__conditions (List[Dict[str, Any]]): Conditions is a list of conditions the CronWorkflow may have

        body_cronWorkflow__status__failed (int): v3.6 and after: Failed counts how many times child workflows failed

        body_cronWorkflow__status__lastScheduledTime (str): Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.

        body_cronWorkflow__status__phase (str): v3.6 and after: Phase is an enum of Active or Stopped. It changes to Stopped when stopStrategy.expression is true

        body_cronWorkflow__status__succeeded (int): v3.6 and after: Succeeded counts how many times child workflows succeeded

        body_namespace (str): OpenAPI parameter corresponding to 'body_namespace'


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /api/v1/cron-workflows/{namespace}")

    params = {}
    data = {}

    flat_body = {}
    if body_createOptions__dryRun is not None:
        flat_body["createOptions__dryRun"] = body_createOptions__dryRun
    if body_createOptions__fieldManager is not None:
        flat_body["createOptions__fieldManager"] = body_createOptions__fieldManager
    if body_createOptions__fieldValidation is not None:
        flat_body["createOptions__fieldValidation"] = body_createOptions__fieldValidation
    if body_cronWorkflow__apiVersion is not None:
        flat_body["cronWorkflow__apiVersion"] = body_cronWorkflow__apiVersion
    if body_cronWorkflow__kind is not None:
        flat_body["cronWorkflow__kind"] = body_cronWorkflow__kind
    if body_cronWorkflow__metadata is not None:
        flat_body["cronWorkflow__metadata"] = body_cronWorkflow__metadata
    if body_cronWorkflow__spec is not None:
        flat_body["cronWorkflow__spec"] = body_cronWorkflow__spec
    if body_cronWorkflow__status__active is not None:
        flat_body["cronWorkflow__status__active"] = body_cronWorkflow__status__active
    if body_cronWorkflow__status__conditions is not None:
        flat_body["cronWorkflow__status__conditions"] = body_cronWorkflow__status__conditions
    if body_cronWorkflow__status__failed is not None:
        flat_body["cronWorkflow__status__failed"] = body_cronWorkflow__status__failed
    if body_cronWorkflow__status__lastScheduledTime is not None:
        flat_body["cronWorkflow__status__lastScheduledTime"] = body_cronWorkflow__status__lastScheduledTime
    if body_cronWorkflow__status__phase is not None:
        flat_body["cronWorkflow__status__phase"] = body_cronWorkflow__status__phase
    if body_cronWorkflow__status__succeeded is not None:
        flat_body["cronWorkflow__status__succeeded"] = body_cronWorkflow__status__succeeded
    if body_namespace is not None:
        flat_body["namespace"] = body_namespace
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/cron-workflows/{path_namespace}", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
