# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/cron-workflows/{namespace}/{name} operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def cron_workflow_service_get_cron_workflow(path_namespace: str, path_name: str, param_getOptions_resource_version: str = None) -> Any:
    """
    Retrieve cron-workflows information

    OpenAPI Description:
        Retrieve cron-workflows information Use when: when you have a specific resource identifier and need its current details. Required: namespace, name

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        path_name (str): Name of the resource to operate on

        param_getOptions_resource_version (str): resource_version sets a constraint on what resource versions a request may be ser...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/cron-workflows/{namespace}/{name}")

    params = {}
    data = {}

    if param_getOptions_resource_version is not None:
        params["getOptions_resource_version"] = (
            str(param_getOptions_resource_version).lower()
            if isinstance(param_getOptions_resource_version, bool)
            else param_getOptions_resource_version
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/cron-workflows/{path_namespace}/{path_name}", method="GET", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def cron_workflow_service_update_cron_workflow(
    path_namespace: str,
    path_name: str,
    body_cronWorkflow_apiVersion: str = None,
    body_cronWorkflow_kind: str = None,
    body_cronWorkflow_metadata: Dict[str, Any] = None,
    body_cronWorkflow_spec: Dict[str, Any] = None,
    body_cronWorkflow_status_active: List[Dict[str, Any]] = None,
    body_cronWorkflow_status_conditions: List[Dict[str, Any]] = None,
    body_cronWorkflow_status_failed: int = None,
    body_cronWorkflow_status_lastScheduledTime: str = None,
    body_cronWorkflow_status_phase: str = None,
    body_cronWorkflow_status_succeeded: int = None,
    body_name: str = None,
    body_namespace: str = None,
) -> Any:
    """
    Update or replace a cron-workflows

    OpenAPI Description:
        Update or replace a cron-workflows Use when: when modifying existing resource configurations or properties. Required: namespace, name, body

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        path_name (str): DEPRECATED: This field is ignored.

        body_cronWorkflow_apiVersion (str): APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources

        body_cronWorkflow_kind (str): Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

        body_cronWorkflow_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

        body_cronWorkflow_spec (Dict[str, Any]): CronWorkflowSpec is the specification of a CronWorkflow

        body_cronWorkflow_status_active (List[Dict[str, Any]]): Active is a list of active workflows stemming from this CronWorkflow

        body_cronWorkflow_status_conditions (List[Dict[str, Any]]): Conditions is a list of conditions the CronWorkflow may have

        body_cronWorkflow_status_failed (int): v3.6 and after: Failed counts how many times child workflows failed

        body_cronWorkflow_status_lastScheduledTime (str): Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.

        body_cronWorkflow_status_phase (str): v3.6 and after: Phase is an enum of Active or Stopped. It changes to Stopped when stopStrategy.expression is true

        body_cronWorkflow_status_succeeded (int): v3.6 and after: Succeeded counts how many times child workflows succeeded

        body_name (str): DEPRECATED: This field is ignored.

        body_namespace (str): OpenAPI parameter corresponding to 'body_namespace'


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making PUT request to /api/v1/cron-workflows/{namespace}/{name}")

    params = {}
    data = {}

    flat_body = {}
    if body_cronWorkflow_apiVersion is not None:
        flat_body["cronWorkflow_apiVersion"] = body_cronWorkflow_apiVersion
    if body_cronWorkflow_kind is not None:
        flat_body["cronWorkflow_kind"] = body_cronWorkflow_kind
    if body_cronWorkflow_metadata is not None:
        flat_body["cronWorkflow_metadata"] = body_cronWorkflow_metadata
    if body_cronWorkflow_spec is not None:
        flat_body["cronWorkflow_spec"] = body_cronWorkflow_spec
    if body_cronWorkflow_status_active is not None:
        flat_body["cronWorkflow_status_active"] = body_cronWorkflow_status_active
    if body_cronWorkflow_status_conditions is not None:
        flat_body["cronWorkflow_status_conditions"] = body_cronWorkflow_status_conditions
    if body_cronWorkflow_status_failed is not None:
        flat_body["cronWorkflow_status_failed"] = body_cronWorkflow_status_failed
    if body_cronWorkflow_status_lastScheduledTime is not None:
        flat_body["cronWorkflow_status_lastScheduledTime"] = body_cronWorkflow_status_lastScheduledTime
    if body_cronWorkflow_status_phase is not None:
        flat_body["cronWorkflow_status_phase"] = body_cronWorkflow_status_phase
    if body_cronWorkflow_status_succeeded is not None:
        flat_body["cronWorkflow_status_succeeded"] = body_cronWorkflow_status_succeeded
    if body_name is not None:
        flat_body["name"] = body_name
    if body_namespace is not None:
        flat_body["namespace"] = body_namespace
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/cron-workflows/{path_namespace}/{path_name}", method="PUT", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def cron_workflow_service_delete_cron_workflow(
    path_namespace: str,
    path_name: str,
    param_delete_options_grace_period_seconds: str = None,
    param_delete_options_preconditions_uid: str = None,
    param_delete_options_preconditions_resource_version: str = None,
    param_delete_options_orphan_dependents: bool = False,
    param_delete_options_propagation_policy: str = None,
    param_delete_options_dry_run: List[str] = None,
    param_delete_options_ignore_store_read_error: bool = False,
) -> Any:
    """
    Delete a cron-workflows

    OpenAPI Description:
        Delete a cron-workflows Use when: when cleaning up resources that are no longer needed. Required: namespace, name

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        path_name (str): Name of the resource to operate on

        param_delete_options_grace_period_seconds (str): The duration in seconds before the object should be deleted. Value must be non-n...

        param_delete_options_preconditions_uid (str): Specifies the target UID. +optional.

        param_delete_options_preconditions_resource_version (str): Specifies the target ResourceVersion +optional.

        param_delete_options_orphan_dependents (bool): Deprecated: please use the PropagationPolicy, this field will be deprecated in 1...

        param_delete_options_propagation_policy (str): Whether and how garbage collection will be performed. Either this field or Orpha...

        param_delete_options_dry_run (List[str]): When present, indicates that modifications should not be persisted. An invalid o...

        param_delete_options_ignore_store_read_error (bool): if set to true, it will trigger an unsafe deletion of the resource in case the n...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making DELETE request to /api/v1/cron-workflows/{namespace}/{name}")

    params = {}
    data = {}

    if param_delete_options_grace_period_seconds is not None:
        params["delete_options_grace_period_seconds"] = (
            str(param_delete_options_grace_period_seconds).lower()
            if isinstance(param_delete_options_grace_period_seconds, bool)
            else param_delete_options_grace_period_seconds
        )

    if param_delete_options_preconditions_uid is not None:
        params["delete_options_preconditions_uid"] = (
            str(param_delete_options_preconditions_uid).lower()
            if isinstance(param_delete_options_preconditions_uid, bool)
            else param_delete_options_preconditions_uid
        )

    if param_delete_options_preconditions_resource_version is not None:
        params["delete_options_preconditions_resource_version"] = (
            str(param_delete_options_preconditions_resource_version).lower()
            if isinstance(param_delete_options_preconditions_resource_version, bool)
            else param_delete_options_preconditions_resource_version
        )

    if param_delete_options_orphan_dependents is not None:
        params["delete_options_orphan_dependents"] = (
            str(param_delete_options_orphan_dependents).lower()
            if isinstance(param_delete_options_orphan_dependents, bool)
            else param_delete_options_orphan_dependents
        )

    if param_delete_options_propagation_policy is not None:
        params["delete_options_propagation_policy"] = (
            str(param_delete_options_propagation_policy).lower()
            if isinstance(param_delete_options_propagation_policy, bool)
            else param_delete_options_propagation_policy
        )

    if param_delete_options_dry_run is not None:
        params["delete_options_dry_run"] = (
            str(param_delete_options_dry_run).lower() if isinstance(param_delete_options_dry_run, bool) else param_delete_options_dry_run
        )

    if param_delete_options_ignore_store_read_error is not None:
        params["delete_options_ignore_store_read_error"] = (
            str(param_delete_options_ignore_store_read_error).lower()
            if isinstance(param_delete_options_ignore_store_read_error, bool)
            else param_delete_options_ignore_store_read_error
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/cron-workflows/{path_namespace}/{path_name}", method="DELETE", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
