# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/sensors/{namespace} operations"""

import logging
from typing import Dict, Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def sensor_service_list_sensors(
    path_namespace: str,
    param_list_options_label_selector: str = None,
    param_list_options_field_selector: str = None,
    param_list_options_watch: bool = False,
    param_list_options_allow_watch_bookmarks: bool = False,
    param_list_options_resource_version: str = None,
    param_list_options_resource_versionMatch: str = None,
    param_list_options_timeout_seconds: str = None,
    param_list_options_limit: str = None,
    param_list_options_continue: str = None,
    param_list_options_send_initial_events: bool = False,
) -> Any:
    """
    Retrieve details of a specific sensors

    OpenAPI Description:
        Retrieve details of a specific sensors Use when: when you need to discover available resources or check what exists. Required: namespace

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        param_list_options_label_selector (str): A selector to restrict the list of returned objects by their labels. Defaults to...

        param_list_options_field_selector (str): A selector to restrict the list of returned objects by their fields. Defaults to...

        param_list_options_watch (bool): Watch for changes to the described resources and return them as a stream of add,...

        param_list_options_allow_watch_bookmarks (bool): allow_watch_bookmarks requests watch events with type "BOOKMARK". Servers that do ...

        param_list_options_resource_version (str): resource_version sets a constraint on what resource versions a request may be ser...

        param_list_options_resource_versionMatch (str): resource_versionMatch determines how resource_version is applied to list calls. It...

        param_list_options_timeout_seconds (str): Timeout for the list/watch call. This limits the duration of the call, regardles...

        param_list_options_limit (str): limit is a maximum number of responses to return for a list call. If more items ...

        param_list_options_continue (str): The continue option should be set when retrieving more results from the server. ...

        param_list_options_send_initial_events (bool): `send_initial_events=true` may be set together with `watch=true`. In that case, th...


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/sensors/{namespace}")

    params = {}
    data = {}

    if param_list_options_label_selector is not None:
        params["list_options_label_selector"] = (
            str(param_list_options_label_selector).lower()
            if isinstance(param_list_options_label_selector, bool)
            else param_list_options_label_selector
        )

    if param_list_options_field_selector is not None:
        params["list_options_field_selector"] = (
            str(param_list_options_field_selector).lower()
            if isinstance(param_list_options_field_selector, bool)
            else param_list_options_field_selector
        )

    if param_list_options_watch is not None:
        params["list_options_watch"] = (
            str(param_list_options_watch).lower() if isinstance(param_list_options_watch, bool) else param_list_options_watch
        )

    if param_list_options_allow_watch_bookmarks is not None:
        params["list_options_allow_watch_bookmarks"] = (
            str(param_list_options_allow_watch_bookmarks).lower()
            if isinstance(param_list_options_allow_watch_bookmarks, bool)
            else param_list_options_allow_watch_bookmarks
        )

    if param_list_options_resource_version is not None:
        params["list_options_resource_version"] = (
            str(param_list_options_resource_version).lower()
            if isinstance(param_list_options_resource_version, bool)
            else param_list_options_resource_version
        )

    if param_list_options_resource_versionMatch is not None:
        params["list_options_resource_versionMatch"] = (
            str(param_list_options_resource_versionMatch).lower()
            if isinstance(param_list_options_resource_versionMatch, bool)
            else param_list_options_resource_versionMatch
        )

    if param_list_options_timeout_seconds is not None:
        params["list_options_timeout_seconds"] = (
            str(param_list_options_timeout_seconds).lower()
            if isinstance(param_list_options_timeout_seconds, bool)
            else param_list_options_timeout_seconds
        )

    if param_list_options_limit is not None:
        params["list_options_limit"] = (
            str(param_list_options_limit).lower() if isinstance(param_list_options_limit, bool) else param_list_options_limit
        )

    if param_list_options_continue is not None:
        params["list_options_continue"] = (
            str(param_list_options_continue).lower() if isinstance(param_list_options_continue, bool) else param_list_options_continue
        )

    if param_list_options_send_initial_events is not None:
        params["list_options_send_initial_events"] = (
            str(param_list_options_send_initial_events).lower()
            if isinstance(param_list_options_send_initial_events, bool)
            else param_list_options_send_initial_events
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/sensors/{path_namespace}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def sensor_service_create_sensor(
    path_namespace: str,
    body_create_options_dry_run: List[str] = None,
    body_create_options_fieldManager: str = None,
    body_create_options_fieldValidation: str = None,
    body_namespace: str = None,
    body_sensor_metadata: Dict[str, Any] = None,
    body_sensor_spec_dependencies: List[Dict[str, Any]] = None,
    body_sensor_spec_errorOnFailedRound: bool = None,
    body_sensor_spec_eventBusName: str = None,
    body_sensor_spec_loggingFields: Dict[str, Any] = None,
    body_sensor_spec_replicas: int = None,
    body_sensor_spec_revisionHistoryLimit: int = None,
    body_sensor_spec_template: Dict[str, Any] = None,
    body_sensor_spec_triggers: List[Dict[str, Any]] = None,
    body_sensor_status_status_conditions: List[Dict[str, Any]] = None,
) -> Any:
    """
        Create a new sensors

        OpenAPI Description:
            Create a new sensors Use when: when initializing new resources based on user requirements. Required: namespace, body

        Args:

            path_namespace (str): Kubernetes namespace to scope the operation

            body_create_options_dry_run (List[str]): OpenAPI parameter corresponding to 'body_create_options_dry_run'

            body_create_options_fieldManager (str): OpenAPI parameter corresponding to 'body_create_options_fieldManager'

            body_create_options_fieldValidation (str): OpenAPI parameter corresponding to 'body_create_options_fieldValidation'

            body_namespace (str): OpenAPI parameter corresponding to 'body_namespace'

            body_sensor_metadata (Dict[str, Any]): ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

            body_sensor_spec_dependencies (List[Dict[str, Any]]): Dependencies is a list of the events that this sensor is dependent on.

            body_sensor_spec_errorOnFailedRound (bool): ErrorOnFailedRound if set to true, marks sensor state as `error` if the previous trigger round fails.
    Once sensor state is set to `error`, no further triggers will be processed.

            body_sensor_spec_eventBusName (str): OpenAPI parameter corresponding to 'body_sensor_spec_eventBusName'

            body_sensor_spec_loggingFields (Dict[str, Any]): OpenAPI parameter corresponding to 'body_sensor_spec_loggingFields'

            body_sensor_spec_replicas (int): OpenAPI parameter corresponding to 'body_sensor_spec_replicas'

            body_sensor_spec_revisionHistoryLimit (int): OpenAPI parameter corresponding to 'body_sensor_spec_revisionHistoryLimit'

            body_sensor_spec_template (Dict[str, Any]): Request body as dictionary. Contains 11 nested properties. See OpenAPI schema for detailed structure.

            body_sensor_spec_triggers (List[Dict[str, Any]]): Triggers is a list of the things that this sensor evokes. These are the outputs from this sensor.

            body_sensor_status_status_conditions (List[Dict[str, Any]]): OpenAPI parameter corresponding to 'body_sensor_status_status_conditions'


        Returns:
            Any: The JSON response from the API call.

        Raises:
            Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /api/v1/sensors/{namespace}")

    params = {}
    data = {}

    flat_body = {}
    if body_create_options_dry_run is not None:
        flat_body["create_options_dry_run"] = body_create_options_dry_run
    if body_create_options_fieldManager is not None:
        flat_body["create_options_fieldManager"] = body_create_options_fieldManager
    if body_create_options_fieldValidation is not None:
        flat_body["create_options_fieldValidation"] = body_create_options_fieldValidation
    if body_namespace is not None:
        flat_body["namespace"] = body_namespace
    if body_sensor_metadata is not None:
        flat_body["sensor_metadata"] = body_sensor_metadata
    if body_sensor_spec_dependencies is not None:
        flat_body["sensor_spec_dependencies"] = body_sensor_spec_dependencies
    if body_sensor_spec_errorOnFailedRound is not None:
        flat_body["sensor_spec_errorOnFailedRound"] = body_sensor_spec_errorOnFailedRound
    if body_sensor_spec_eventBusName is not None:
        flat_body["sensor_spec_eventBusName"] = body_sensor_spec_eventBusName
    if body_sensor_spec_loggingFields is not None:
        flat_body["sensor_spec_loggingFields"] = body_sensor_spec_loggingFields
    if body_sensor_spec_replicas is not None:
        flat_body["sensor_spec_replicas"] = body_sensor_spec_replicas
    if body_sensor_spec_revisionHistoryLimit is not None:
        flat_body["sensor_spec_revisionHistoryLimit"] = body_sensor_spec_revisionHistoryLimit
    if body_sensor_spec_template is not None:
        flat_body["sensor_spec_template"] = body_sensor_spec_template
    if body_sensor_spec_triggers is not None:
        flat_body["sensor_spec_triggers"] = body_sensor_spec_triggers
    if body_sensor_status_status_conditions is not None:
        flat_body["sensor_status_status_conditions"] = body_sensor_status_status_conditions
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/sensors/{path_namespace}", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
