# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/workflows/{namespace}/{name} operations"""

import logging
from typing import Any, List
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def workflow_service_get_workflow(
    path_namespace: str, path_name: str, param_getOptions_resource_version: str = None, param_fields: str = None
) -> Any:
    """
    Retrieve workflows information

    OpenAPI Description:
        Retrieve workflows information Use when: when you have a specific resource identifier and need its current details. Required: namespace, name

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        path_name (str): Name of the resource to operate on

        param_getOptions_resource_version (str): resource_version sets a constraint on what resource versions a request may be ser...

        param_fields (str): Fields to be included or excluded in the response. e.g. "spec,status.phase", "-status.nodes".


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api/v1/workflows/{namespace}/{name}")

    params = {}
    data = {}

    if param_getOptions_resource_version is not None:
        params["getOptions_resource_version"] = (
            str(param_getOptions_resource_version).lower()
            if isinstance(param_getOptions_resource_version, bool)
            else param_getOptions_resource_version
        )

    if param_fields is not None:
        params["fields"] = str(param_fields).lower() if isinstance(param_fields, bool) else param_fields

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/workflows/{path_namespace}/{path_name}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def workflow_service_delete_workflow(
    path_namespace: str,
    path_name: str,
    param_delete_options_grace_period_seconds: str = None,
    param_delete_options_preconditions_uid: str = None,
    param_delete_options_preconditions_resource_version: str = None,
    param_delete_options_orphan_dependents: bool = False,
    param_delete_options_propagation_policy: str = None,
    param_delete_options_dry_run: List[str] = None,
    param_delete_options_ignore_store_read_error: bool = False,
    param_force: bool = False,
) -> Any:
    """
    Delete a workflows

    OpenAPI Description:
        Delete a workflows Use when: when cleaning up resources that are no longer needed. Required: namespace, name

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        path_name (str): Name of the resource to operate on

        param_delete_options_grace_period_seconds (str): The duration in seconds before the object should be deleted. Value must be non-n...

        param_delete_options_preconditions_uid (str): Specifies the target UID. +optional.

        param_delete_options_preconditions_resource_version (str): Specifies the target ResourceVersion +optional.

        param_delete_options_orphan_dependents (bool): Deprecated: please use the PropagationPolicy, this field will be deprecated in 1...

        param_delete_options_propagation_policy (str): Whether and how garbage collection will be performed. Either this field or Orpha...

        param_delete_options_dry_run (List[str]): When present, indicates that modifications should not be persisted. An invalid o...

        param_delete_options_ignore_store_read_error (bool): if set to true, it will trigger an unsafe deletion of the resource in case the n...

        param_force (bool): Optional boolean parameter


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making DELETE request to /api/v1/workflows/{namespace}/{name}")

    params = {}
    data = {}

    if param_delete_options_grace_period_seconds is not None:
        params["delete_options_grace_period_seconds"] = (
            str(param_delete_options_grace_period_seconds).lower()
            if isinstance(param_delete_options_grace_period_seconds, bool)
            else param_delete_options_grace_period_seconds
        )

    if param_delete_options_preconditions_uid is not None:
        params["delete_options_preconditions_uid"] = (
            str(param_delete_options_preconditions_uid).lower()
            if isinstance(param_delete_options_preconditions_uid, bool)
            else param_delete_options_preconditions_uid
        )

    if param_delete_options_preconditions_resource_version is not None:
        params["delete_options_preconditions_resource_version"] = (
            str(param_delete_options_preconditions_resource_version).lower()
            if isinstance(param_delete_options_preconditions_resource_version, bool)
            else param_delete_options_preconditions_resource_version
        )

    if param_delete_options_orphan_dependents is not None:
        params["delete_options_orphan_dependents"] = (
            str(param_delete_options_orphan_dependents).lower()
            if isinstance(param_delete_options_orphan_dependents, bool)
            else param_delete_options_orphan_dependents
        )

    if param_delete_options_propagation_policy is not None:
        params["delete_options_propagation_policy"] = (
            str(param_delete_options_propagation_policy).lower()
            if isinstance(param_delete_options_propagation_policy, bool)
            else param_delete_options_propagation_policy
        )

    if param_delete_options_dry_run is not None:
        params["delete_options_dry_run"] = (
            str(param_delete_options_dry_run).lower() if isinstance(param_delete_options_dry_run, bool) else param_delete_options_dry_run
        )

    if param_delete_options_ignore_store_read_error is not None:
        params["delete_options_ignore_store_read_error"] = (
            str(param_delete_options_ignore_store_read_error).lower()
            if isinstance(param_delete_options_ignore_store_read_error, bool)
            else param_delete_options_ignore_store_read_error
        )

    if param_force is not None:
        params["force"] = str(param_force).lower() if isinstance(param_force, bool) else param_force

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/api/v1/workflows/{path_namespace}/{path_name}", method="DELETE", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
