# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/archived-workflows-label-values operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def archived_workflow_service_list_archived_workflow_label_values(
  param_listOptions_labelSelector: str = None,
  param_listOptions_fieldSelector: str = None,
  param_listOptions_watch: bool = False,
  param_listOptions_allowWatchBookmarks: bool = False,
  param_listOptions_resourceVersion: str = None,
  param_listOptions_resourceVersionMatch: str = None,
  param_listOptions_timeoutSeconds: int = None,
  param_listOptions_limit: int = None,
  param_listOptions_continue: str = None,
  param_listOptions_sendInitialEvents: str = None,
  param_namespace: str = None,
) -> Any:
  """
  List or query archived-workflows-label-values

  OpenAPI Description:
      Lists label values of archived workflows. Use when: filtering or categorizing archived workflows based on specific labels.

  Args:

      param_listOptions_labelSelector (str): Criteria to filter results by labels (e.g., app=nginx)

      param_listOptions_fieldSelector (str): Criteria to filter results by specific fields (e.g., status=completed)

      param_listOptions_watch (bool): Enable streaming updates for resource changes when true

      param_listOptions_allowWatchBookmarks (bool): Enable bookmark events in watch mode when true

      param_listOptions_resourceVersion (str): "Specify resource version to filter results for consistency"

      param_listOptions_resourceVersionMatch (str): Controls resource version matching for list calls (e.g., exact, notOlderThan)

      param_listOptions_timeoutSeconds (int): Maximum time to wait for response in seconds (e.g., 30)

      param_listOptions_limit (int): "Maximum archived workflows to return (e.g., 100)"

      param_listOptions_continue (str): Pagination token for next page of results

      param_listOptions_sendInitialEvents (str): Send initial events in watch stream when true

      param_namespace (str): "Kubernetes namespace to filter archived workflows"


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /api/v1/archived-workflows-label-values")

  params = {}
  data = {}

  if param_listOptions_labelSelector is not None:
    params["listOptions_labelSelector"] = (
      str(param_listOptions_labelSelector).lower() if isinstance(param_listOptions_labelSelector, bool) else param_listOptions_labelSelector
    )

  if param_listOptions_fieldSelector is not None:
    params["listOptions_fieldSelector"] = (
      str(param_listOptions_fieldSelector).lower() if isinstance(param_listOptions_fieldSelector, bool) else param_listOptions_fieldSelector
    )

  if param_listOptions_watch is not None:
    params["listOptions_watch"] = (
      str(param_listOptions_watch).lower() if isinstance(param_listOptions_watch, bool) else param_listOptions_watch
    )

  if param_listOptions_allowWatchBookmarks is not None:
    params["listOptions_allowWatchBookmarks"] = (
      str(param_listOptions_allowWatchBookmarks).lower()
      if isinstance(param_listOptions_allowWatchBookmarks, bool)
      else param_listOptions_allowWatchBookmarks
    )

  if param_listOptions_resourceVersion is not None:
    params["listOptions_resourceVersion"] = (
      str(param_listOptions_resourceVersion).lower()
      if isinstance(param_listOptions_resourceVersion, bool)
      else param_listOptions_resourceVersion
    )

  if param_listOptions_resourceVersionMatch is not None:
    params["listOptions_resourceVersionMatch"] = (
      str(param_listOptions_resourceVersionMatch).lower()
      if isinstance(param_listOptions_resourceVersionMatch, bool)
      else param_listOptions_resourceVersionMatch
    )

  if param_listOptions_timeoutSeconds is not None:
    params["listOptions_timeoutSeconds"] = (
      str(param_listOptions_timeoutSeconds).lower()
      if isinstance(param_listOptions_timeoutSeconds, bool)
      else param_listOptions_timeoutSeconds
    )

  if param_listOptions_limit is not None:
    params["listOptions_limit"] = (
      str(param_listOptions_limit).lower() if isinstance(param_listOptions_limit, bool) else param_listOptions_limit
    )

  if param_listOptions_continue is not None:
    params["listOptions_continue"] = (
      str(param_listOptions_continue).lower() if isinstance(param_listOptions_continue, bool) else param_listOptions_continue
    )

  if param_listOptions_sendInitialEvents is not None:
    params["listOptions_sendInitialEvents"] = (
      str(param_listOptions_sendInitialEvents).lower()
      if isinstance(param_listOptions_sendInitialEvents, bool)
      else param_listOptions_sendInitialEvents
    )

  if param_namespace is not None:
    params["namespace"] = str(param_namespace).lower() if isinstance(param_namespace, bool) else param_namespace

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request("/api/v1/archived-workflows-label-values", method="GET", params=params, data=data)

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
