# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName} operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def artifact_service_get_artifact_file(
    path_namespace: str, path_id_discriminator: str, path_id: str, path_node_id: str, path_artifact_name: str, path_artifact_discriminator: str
) -> Any:
    """
    Retrieve artifact-files information

    OpenAPI Description:
        Retrieve artifact-files information Use when: when you have a specific resource identifier and need its current details

    Args:

        path_namespace (str): Kubernetes namespace to scope the operation

        path_id_discriminator (str): Required string parameter

        path_id (str): Required string parameter

        path_node_id (str): Required string parameter

        path_artifact_name (str): Name of the resource to operate on

        path_artifact_discriminator (str): Required string parameter


    Returns:
        Any: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/artifact-files/{path_namespace}/{path_id_discriminator}/{path_id}/{path_node_id}/{path_artifact_discriminator}/{path_artifact_name}",
        method="GET",
        params=params,
        data=data,
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
