# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /artifacts/{namespace}/{name}/{nodeId}/{artifactName} operations"""

import logging
from typing import Any
from mcp_argo_workflows.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def artifact_service_get_output_artifact(path_namespace: str, path_name: str, path_nodeId: str, path_artifactName: str) -> Any:
  """
  Get an output artifact.

  OpenAPI Description:
      Retrieves an output artifact by name and node ID. Use when: accessing specific artifact data for analysis or debugging within a workflow.

  Args:

      path_namespace (str): "Kubernetes namespace to locate the artifact"

      path_name (str): "Artifact name to retrieve within the specified namespace"

      path_nodeId (str): "Unique identifier of the node to retrieve artifacts from"

      path_artifactName (str): Specifies the name of the artifact to retrieve from the node.


  Returns:
      Any: The JSON response from the API call.

  Raises:
      Exception: If the API request fails or returns an error.
  """
  logger.debug("Making GET request to /artifacts/{namespace}/{name}/{nodeId}/{artifactName}")

  params = {}
  data = {}

  flat_body = {}
  data = assemble_nested_body(flat_body)

  success, response = await make_api_request(
    f"/artifacts/{path_namespace}/{path_name}/{path_nodeId}/{path_artifactName}", method="GET", params=params, data=data
  )

  if not success:
    logger.error(f"Request failed: {response.get('error')}")
    return {"error": response.get("error", "Request failed")}
  return response
